- packages/config-ui/src/feedback-config/__tests__/__snapshots__/feedback-config.test.jsx.snap
- packages/config-ui/src/feedback-config/__tests__/feedback-config.test.jsx
- packages/config-ui/src/feedback-config/index.jsx
Not expanded:
Expanded:
Nicely animated in-between too. Please let me know what you think @edeustace.
CC: @evaneus 
If there's anything else that we would like adjusted, let me know.
> update feedback ui for config views [ch83]

- packages/charting-config/package.json
- packages/charting-config/src/graph-attribute-config.jsx
- packages/charting-config/src/index.jsx
#26 is a pre-requisite for this one, that'll need to go first!
> feat(charting-config): update inputs to no longer pass through invalid model updates

- packages/editable-html/src/plugins/image/index.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
Image plugin was missing a done button.
> fix(editable-html): fix image plugin done button

- jest.config.js
- packages/text-select/src/tokenizer/__tests__/__snapshots__/controls.test.jsx.snap
- packages/text-select/src/tokenizer/__tests__/__snapshots__/index.test.jsx.snap
- packages/text-select/src/tokenizer/__tests__/builder.test.js
- packages/text-select/src/tokenizer/__tests__/controls.test.jsx
- packages/text-select/src/tokenizer/__tests__/index.test.jsx
- packages/text-select/src/tokenizer/builder.js
- packages/text-select/src/tokenizer/controls.jsx
- packages/text-select/src/tokenizer/index.jsx
Completes this: https://github.com/pie-framework/pie-elements/issues/88
> fix(add-paragraph): added a paragraph builder for tokens

- packages/editable-html/src/plugins/index.jsx
- packages/editable-html/src/plugins/table/index.jsx
- packages/editable-html/src/plugins/table/table-toolbar.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
Fixes these 2 issues: [1](https://github.com/pie-framework/pie-elements/issues/73) and [2](https://github.com/pie-framework/pie-elements/issues/74).
> Added image and math support to the table plugin

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/toolbar/editor-and-toolbar.jsx
Fixes [this](https://github.com/pie-framework/pie-elements/issues/108) issue.
> editable html field expanding to max

- packages/editable-html/package.json
- packages/math-input/package.json
- packages/math-input/src/extras.jsx
- packages/math-input/src/icons/base.jsx
- packages/math-input/src/icons/index.jsx
After this is merged `math-input` and `editable-html` need to be released and after that the `editable-html` package.json needs to be updated with the new `math-input` version
> feat(math-input): added some new symbols to the math-input

- packages/editable-html/src/plugins/table/index.jsx
Fixes [this](https://github.com/pie-framework/pie-elements/issues/71) issue
> fix(editable-html): increased the initial width of the table cell

- packages/editable-html/src/plugins/list/__tests__/index.test.js
- packages/editable-html/src/plugins/list/index.jsx
- packages/editable-html/src/plugins/table/index.jsx
Fixes [this](https://github.com/pie-framework/pie-elements/issues/66) issue
> fix(editable-html): list inside table

- packages/demo/pages/editable-html.js
- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/image/index.jsx
- packages/editable-html/src/plugins/toolbar/__tests__/__snapshots__/default-toolbar.test.jsx.snap
- packages/editable-html/src/plugins/toolbar/__tests__/__snapshots__/toolbar.test.jsx.snap
- packages/editable-html/src/plugins/toolbar/__tests__/default-toolbar.test.jsx
- packages/editable-html/src/plugins/toolbar/__tests__/toolbar.test.jsx
- packages/editable-html/src/plugins/toolbar/default-toolbar.jsx
- packages/editable-html/src/plugins/toolbar/editor-and-toolbar.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
This prop allows you to make runtime changes that the plugin can make
use of while executing.
> At the moment it's only used to render toolbar buttons, but if needed
we can get the props to pass down to the render methods of each plugin.
> feat: add new prop 'pluginProps'

- packages/math-input/src/horizontal-keypad.jsx
- packages/math-input/src/keypad/__tests__/__snapshots__/index.test.jsx.snap
- packages/math-input/src/keypad/index.jsx
> feat(math-input): no decimals support added

- packages/math-toolbar/src/editor-and-pad.jsx
- packages/math-toolbar/src/index.jsx
> feat(math-toolbar): no decimals support added

- packages/demo/pages/config-ui/config-layout.js
layout.OldConfigLayout was throwing an error (because it does not exist).
> fix(demo): Fixed demo bug.

- packages/math-input/src/keypad/index.jsx
> chore: math-input equals sign should have the same background color as other operators

- packages/math-input/src/keys/trigonometry.js
> fix(math-input): fix trigo keypad buttons

- packages/math-toolbar/src/done-button.jsx
- packages/math-toolbar/src/editor-and-pad.jsx
- packages/math-toolbar/src/index.jsx
And various small other fixes.
> fix(math-toolbar): fix width styling

- packages/rubric/src/authoring.jsx
> fix: small styling tweaks

- packages/demo/pages/editable-html.js
- packages/editable-html/src/plugins/math/index.jsx
https://app.clubhouse.io/keydatasystems/story/2178/math-formula-editor-functionality-for-extended-text-items
> fix: keypadMode not updating

- packages/rubric/src/authoring.jsx
> fix(rubric): exclude zero checkbox not functional

- packages/rubric/src/authoring.jsx
Rubric model maxPoints was not updating properly.
> fix: update maxPoints number.

- packages/math-input/src/mq/static.jsx
> fix(math-input): fix Static rootblock logic, failsafe for finding math block id ch3518

- packages/math-input/src/keypad/index.jsx
(because they are overwritten)
> fix: PD-157: In IBX specifically, characters on math editors are too small.

- packages/categorize/src/__tests__/index.test.js
- packages/categorize/src/index.js
There was an error that caused crashing when trying to apply reduce on undefined.
> fix: PD-193: Categorize authoring feature not working on pie-website

- packages/correct-answer-toggle/package.json
- packages/correct-answer-toggle/src/styles.js
- packages/demo/pages/render-ui.js
- packages/render-ui/README.md
- packages/render-ui/src/__tests__/color.test.js
- packages/render-ui/src/color.js
- packages/render-ui/src/feedback.jsx
- packages/render-ui/src/index.js
* add color module
* update correct-answer-toggle to use `color.text()`
* update feedback to use `color.correct()` and `color.incorrect()`
> feat: add color custom properties PD-308

- packages/mask-markup/src/components/dropdown.jsx
> feat(mask-markup): inline-dropdown color treatment fixed

- packages/render-ui/src/preview-prompt.jsx
Also, I think the last person who worked on this file needs to update their tabbing/spacing options - we use LF.
> fix(render-ui): make sure prompt replace has a value

- packages/text-select/src/token-select/token.jsx
https://illuminate.atlassian.net/browse/PD-898
> fix(text-select): fix space between lines - PD-898

- packages/categorize/src/index.js
https://illuminate.atlassian.net/browse/PD-896?atlOrigin=eyJpIjoiYjQ4MTE2M2Y0NzhmNDljN2FjZGM5NjA1NmE2YzY4YmUiLCJwIjoiaiJ9
> fix(categorize): add alternate responses to updated model-PD-896

- packages/config-ui/src/choice-configuration/__tests__/__snapshots__/index.test.jsx.snap
- packages/config-ui/src/choice-configuration/index.jsx
https://illuminate.atlassian.net/browse/PD-900?atlOrigin=eyJpIjoiNjdhZDYzMzJjNmM2NGVkZDhjZTg5ODRiM2ZkNzhkYmEiLCJwIjoiaiJ9
> fix(config-ui): hide feedback for author if feedback is not enabled-PD-900

- packages/text-select/src/token-select/__tests__/__snapshots__/index.test.jsx.snap
- packages/text-select/src/token-select/__tests__/__snapshots__/token.test.jsx.snap
- packages/text-select/src/token-select/__tests__/index.test.jsx
- packages/text-select/src/token-select/__tests__/token.test.jsx
- packages/text-select/src/token-select/index.jsx
- packages/text-select/src/token-select/token.jsx
- packages/text-select/src/tokenizer/__tests__/__snapshots__/token-text.test.jsx.snap
- packages/text-select/src/tokenizer/__tests__/builder.test.js
- packages/text-select/src/tokenizer/__tests__/token-text.test.jsx
- packages/text-select/src/tokenizer/builder.js
- packages/text-select/src/tokenizer/token-text.jsx
PD-134: feat(tokens): made sure paragraphs and new lines are working in select text
> PD-134: feat(tokens): made sure paragraphs and new lines are working in select text

- packages/render-ui/src/collapsible/index.jsx
https://illuminate.atlassian.net/browse/PD-772
> fix(render-ui): render math for collapsible to fix PD-772

- packages/text-select/src/token-select/token.jsx
https://illuminate.atlassian.net/browse/PD-860
> fix(text-select): fix padding for tokens in order to fix PD-860

- packages/graphing/src/graph-with-controls.jsx
https://illuminate.atlassian.net/browse/PD-24
> fix(graphing): in OT buttons and tool labels are too small, override fontSize of 0.8125rem and fontSize of 0.8125rem PD-24

- packages/text-select/src/token-select/index.jsx
https://illuminate.atlassian.net/browse/PD-749
> fix(text-select): fix layout for legacy items with line number - PD-749

- packages/editable-html/src/__tests__/editor.test.jsx
- packages/editable-html/src/editor.jsx
https://illuminate.atlassian.net/browse/PD-694
> fix(editable-html): add min and max height to fix PD-694

- packages/editable-html/src/plugins/respArea/index.jsx
- packages/editable-html/src/plugins/toolbar/__tests__/__snapshots__/default-toolbar.test.jsx.snap
- packages/editable-html/src/plugins/toolbar/__tests__/__snapshots__/toolbar.test.jsx.snap
- packages/editable-html/src/plugins/toolbar/__tests__/default-toolbar.test.jsx
- packages/editable-html/src/plugins/toolbar/default-toolbar.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
https://illuminate.atlassian.net/browse/PD-778
> fix(editable-html): add delete button for response area PD-778

- packages/graphing/src/axis/__tests__/__snapshots__/axes.test.jsx.snap
- packages/graphing/src/axis/__tests__/axes.test.jsx
- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/graph.jsx
https://illuminate.atlassian.net/browse/PD-529
> fix(graphing): positioning of the numeric labels on the x- and y- axes for 0 and -1 PD-529

- packages/math-input/src/keypad/index.jsx
- packages/math-toolbar/src/editor-and-pad.jsx
- packages/math-toolbar/src/math-preview.jsx
https://illuminate.atlassian.net/browse/PD-774
> fix: override math input and math toolbar style for ibx PD-774

- packages/config-ui/src/__tests__/__snapshots__/settings-panel.test.js.snap
- packages/config-ui/src/__tests__/settings-panel.test.js
- packages/demo/pages/config-ui/settings-panel.js
- packages/demo/pages/editable-html.js
- packages/demo/pages/math-input.js
- packages/math-input/src/keys/__tests__/utils.test.js
- packages/math-input/src/keys/grades.js
- packages/math-toolbar/src/editor-and-pad.jsx
- packages/math-toolbar/src/index.jsx
https://illuminate.atlassian.net/browse/PD-870
> fix: rename the 'Everything' math editor as the 'Miscellaneous' math editor

- packages/math-toolbar/src/editor-and-pad.jsx
https://illuminate.atlassian.net/browse/PD-48
> fix(math-toolbar): override style for ray PD-48

- packages/mask-markup/src/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-726
> fix(mask-markup): increase height for drag-in-the-blank chip PD-726

- packages/config-ui/src/settings/panel.jsx
https://illuminate.atlassian.net/browse/PD-269
> fix(config-ui): set same font-size for labels in settings panel PD-269

- packages/demo/pages/graphing/index.js
- packages/graphing/src/__tests__/utils.test.js
- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/utils.js
- packages/plot/src/__tests__/utils.test.js
- packages/plot/src/root.jsx
- packages/plot/src/utils.js
https://illuminate.atlassian.net/browse/PD-988
> fix(graphing): increase height and width for longer labels for the two axes

- packages/graphing/src/tools/shared/point/arrow.jsx
- packages/graphing/src/tools/vector/component.jsx
- packages/graphing/src/utils.js
PD-495
My solution is to move the arrow with half of its height to the starting point and change x / y end point of the line depending on angle's direction.
> fix(graphing): fix arrow positioning

- packages/graphing/src/tools/shared/point/arrow.jsx
[PD-495](https://illuminate.atlassian.net/secure/RapidBoard.jspa?rapidView=439&projectKey=PD&modal=detail&selectedIssue=PD-495&assignee=6050632860d39e006f57c440)
My previous fix was reverted because it supported only 4 angles, but this fix should work for any vector angle.
> fix(graphing): fix arrow positioning for any angle PD-495

- packages/editable-html/src/plugins/math/index.jsx
- packages/editable-html/src/plugins/respArea/index.jsx
https://illuminate.atlassian.net/browse/PD-793
> PD-793: feat(plugins): space added before void element after new line

- packages/charting/src/axes.jsx
- packages/charting/src/common/__tests__/__snapshots__/drag-handle.test.jsx.snap
- packages/charting/src/common/drag-handle.jsx
- packages/charting/src/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-43
https://illuminate.atlassian.net/browse/PD-921
> fix charting style PD-921, PD-43

- packages/editable-html/src/__tests__/serialization.test.js
- packages/editable-html/src/serialization.jsx
PD-792: feat(serialiation): removed br handling that is not needed anymore
> PD-792: feat(serialiation): removed br handling that is not needed anymore

- packages/mask-markup/src/components/__tests__/__snapshots__/blank.test.js.snap
- packages/mask-markup/src/components/blank.jsx
In a In a DITB item where placing an answer into a blank changes the line breaks, UI weirdness results
https://illuminate.atlassian.net/browse/PD-605
> fix(mask-markup): when placing an answer into a blank changes the line breaks, UI weirdness results PD-605

- packages/demo/pages/rubric/index.js
- packages/rubric/src/__tests__/rubric.test.jsx
- packages/rubric/src/authoring.jsx
- packages/rubric/src/point-menu.jsx
https://illuminate.atlassian.net/browse/PD-623
> feat(rubric): Include sample correct answers when displaying a rubric PD-623

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
https://illuminate.atlassian.net/browse/PD-1106
> fix(multi-trait-rubric): Added right and left alignment for the toolbar - PD-1106

- packages/editable-html/src/editor.jsx
https://illuminate.atlassian.net/browse/PD-294
> fix(inline-dropdown): Called onBlur on editable-html - PD-294

- packages/mask-markup/src/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-1120
> fix(mask-markup): Fixed DITB image-based tokens to be draggable - PD-1120

- packages/mask-markup/src/components/__tests__/__snapshots__/dropdown.test.js.snap
- packages/mask-markup/src/components/dropdown.jsx
https://illuminate.atlassian.net/browse/PD-1142
> fix(mask-markup): set max fontSize for dropdown items to fix PD-1142

- packages/charting/src/line/common/line.jsx
https://illuminate.atlassian.net/browse/PD-31
> fix(charting): Fixed the wrong horizontal position of a point on Line Dot - PD-31

- packages/text-select/src/token-select/__tests__/__snapshots__/index.test.jsx.snap
- packages/text-select/src/token-select/token.jsx
https://illuminate.atlassian.net/browse/PD-1154
> fix(text-select): select text view mode should use black for text color PD-1154

- packages/editable-html/src/plugins/media/media-dialog.js
Also fixed the input text that doesn't change after entering a valid audio URL
https://illuminate.atlassian.net/browse/PD-1082
> fix(editable-html): Fixed error checking makes it difficult to type a URL - PD-1082

- packages/text-select/src/token-select/index.jsx
https://illuminate.atlassian.net/browse/PD-1038
> fix(text-select): fix incorrect indenting PD-1038

- packages/text-select/src/token-select/__tests__/index.test.jsx
- packages/text-select/src/token-select/index.jsx
https://illuminate.atlassian.net/browse/PD-958
> feat(text-select): when select-text item permits only one selection, change behavior of gather PD-958

- packages/editable-html/src/plugins/media/media-dialog.js
https://illuminate.atlassian.net/browse/PD-832
> fix(editable-html): insert video should not accept audio and vice versa PD-832

- packages/charting/src/chart.jsx
https://illuminate.atlassian.net/browse/PD-535
> fix(charting): Updated categories filtration - PD-535

- packages/charting/src/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-29
> fix(charting): override style to remove grey background behind labels in IBX PD-29

- packages/graphing/src/tools/circle/component.jsx
- packages/graphing/src/tools/point/__tests__/component.test.jsx
- packages/graphing/src/tools/point/component.jsx
- packages/graphing/src/tools/polygon/__tests__/__snapshots__/component.test.jsx.snap
- packages/graphing/src/tools/polygon/component.jsx
- packages/graphing/src/tools/shared/line/index.jsx
- packages/graphing/src/utils.js
https://illuminate.atlassian.net/browse/PD-486
> feat(graphing): Added the ability to label shapes other than point - PD-486

- packages/editable-html/src/plugins/table/__tests__/index.test.jsx
- packages/editable-html/src/plugins/table/index.jsx
fix(table): made sure table block is not the latest node in the document [PD-341]
> fix(table): made sure table block is not the latest node in the document [PD-341]

- packages/graphing/src/__tests__/__snapshots__/toggle-bar.test.jsx.snap
- packages/graphing/src/toggle-bar.jsx
https://illuminate.atlassian.net/browse/PD-545/
> fix(graphing): Removed non-functional buttons PD-545

- packages/config-ui/src/settings/index.js
- packages/config-ui/src/settings/panel.jsx
- packages/graphing/src/__tests__/__snapshots__/graph.test.jsx.snap
- packages/graphing/src/axis/__tests__/axes.test.jsx
- packages/graphing/src/axis/axes.jsx
https://illuminate.atlassian.net/browse/PD-483
**NEEDS TO BE MERGED BEFORE https://github.com/pie-framework/pie-elements/pull/603**
> feat: config-ui add checkboxes, control graphing arrows PD-483

- packages/editable-html/src/serialization.jsx
- packages/mask-markup/src/serialization.js
https://illuminate.atlassian.net/browse/PD-859
> fix(mask-markup, editable-html): Updated serialization PD-859

- packages/editable-html/src/index.jsx
**NEEDS TO BE MERGED BEFORE https://github.com/pie-framework/pie-elements/pull/615** 
https://illuminate.atlassian.net/browse/PD-601
> feat(editable-html): add prop that allows editable-html fields to be validated PD-601

- packages/editable-html/src/__tests__/editor.test.jsx
- packages/editable-html/src/editor.jsx
- packages/editable-html/src/index.jsx
- packages/editable-html/src/plugins/respArea/inline-dropdown/index.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
- packages/render-ui/src/input-container.jsx
https://illuminate.atlassian.net/browse/PD-1230
**NEEDS TO BE MERGED BEFORE https://github.com/pie-framework/pie-elements/pull/629**
> fix(editable-html): add refs for editors, fix propTypes warnings for PD-1230

- packages/demo/pages/graphing/index.js
- packages/graphing/src/__tests__/__snapshots__/graph-with-controls.test.jsx.snap
- packages/graphing/src/__tests__/__snapshots__/mark-label.test.jsx.snap
- packages/graphing/src/__tests__/graph-with-controls.test.jsx
- packages/graphing/src/__tests__/mark-label.test.jsx
- packages/graphing/src/coordinates-label.jsx
- packages/graphing/src/graph-with-controls.jsx
- packages/graphing/src/graph.jsx
- packages/graphing/src/mark-label.jsx
- packages/graphing/src/tools/circle/__tests__/__snapshots__/component.test.jsx.snap
- packages/graphing/src/tools/circle/component.jsx
- packages/graphing/src/tools/point/component.jsx
- packages/graphing/src/tools/polygon/__tests__/__snapshots__/component.test.jsx.snap
- packages/graphing/src/tools/polygon/component.jsx
- packages/graphing/src/tools/shared/line/__tests__/__snapshots__/index.test.jsx.snap
- packages/graphing/src/tools/shared/line/index.jsx
- packages/graphing/src/tools/shared/point/base-point.jsx
- packages/graphing/src/utils.js
https://illuminate.atlassian.net/browse/PD-188
> feat(graphing): Display point coordinates on hover PD-188

- packages/text-select/src/tokenizer/index.jsx
https://illuminate.atlassian.net/browse/PD-477
> fix(text-select): Fixed white space collapse PD-477

- packages/text-select/src/__tests__/utils.test.jsx
- packages/text-select/src/index.js
- packages/text-select/src/utils.js
**NEEDS TO BE MERGED BEFORE https://github.com/pie-framework/pie-elements/pull/661**
> fix(text-select): move prepareText function from pie-elements

- packages/math-toolbar/src/editor-and-pad.jsx
https://illuminate.atlassian.net/browse/PD-1266
> feat(math-toolbar): default to the grade 8 editor PD-1266

- packages/math-toolbar/src/math-preview.jsx
https://illuminate.atlassian.net/browse/PD-1265
> fix: override arrow style for ray PD-1265

- packages/math-input/src/__tests__/__snapshots__/math-input-test.jsx.snap
- packages/math-input/src/horizontal-keypad.jsx
- packages/math-input/src/keys/basic-operators.js
- packages/math-input/src/keys/grades.js
- packages/math-input/src/keys/misc.js
fix for: PD-1251,  PD-1252,  PD-1253,  PD-1254,  PD-1255,  PD-1256,  PD-1257
https://illuminate.atlassian.net/browse/PD-1251
https://illuminate.atlassian.net/browse/PD-1252
https://illuminate.atlassian.net/browse/PD-1253
https://illuminate.atlassian.net/browse/PD-1254
https://illuminate.atlassian.net/browse/PD-1255
https://illuminate.atlassian.net/browse/PD-1256
https://illuminate.atlassian.net/browse/PD-1257
> fix(math-input): Fixed custom keys behavior and changed label for (),[] and absolute value 

- packages/text-select/src/tokenizer/__tests__/__snapshots__/token-text.test.jsx.snap
- packages/text-select/src/tokenizer/__tests__/token-text.test.jsx
- packages/text-select/src/tokenizer/token-text.jsx
PD-1145: feat(tokens): made sure manual token creation works with new lines as well
> PD-1145: feat(tokens): made sure manual token creation works with new lines as well

- packages/math-input/src/keys/constants.js
https://illuminate.atlassian.net/browse/PD-1280
> fix(math-input): fix e button on advanced algebra math editor PD-1280

- packages/math-input/src/mq/static.jsx
discovered here: https://illuminate.atlassian.net/browse/CTT-194.
> fix(math-input): default latex when received is wrong

- packages/math-input/src/keypad/index.jsx
- packages/math-toolbar/src/editor-and-pad.jsx
- packages/math-toolbar/src/math-preview.jsx
https://illuminate.atlassian.net/browse/PD-1264
> fix(math-toolbar): Fixed arrows for pits

- packages/charting/src/chart.jsx
https://illuminate.atlassian.net/browse/PD-531
> fix(charting): Displayed the entire rightmost category label when space available PD-531

- packages/math-input/src/keys/geometry.js
https://illuminate.atlassian.net/browse/PD-368?focusedCommentId=831787
> fix(math-input): render measured angle as m + angle sign PD-368

- packages/demo/pages/rubric/index.js
- packages/rubric/src/authoring.jsx
https://illuminate.atlassian.net/browse/PD-1313
> feat(rubric): Added Studio support: Treat 'null' as null value for sample answer PD-1313

- packages/math-input/src/keypad/index.jsx
- packages/math-input/src/keys/geometry.js
https://illuminate.atlassian.net/browse/PD-1315
> fix(math-input): Made segment, ray and line buttons more consistent PD-1315

- packages/math-input/src/keys/log.js
https://illuminate.atlassian.net/browse/PD-1311
> fix(math-input): create proper latex expression for log base button PD-1311

- packages/editable-html/src/plugins/table/__tests__/index.test.jsx
- packages/editable-html/src/plugins/table/index.jsx
- packages/editable-html/src/serialization.jsx
fix(serialization): made sure that units are not added to numbered values when they are encountered [PD-722]
> fix(serialization): made sure that units are not added to numbered values when they are encountered [PD-722]

- packages/mask-markup/src/components/__tests__/__snapshots__/correct-input.test.js.snap
- packages/mask-markup/src/components/correct-input.jsx
- packages/mask-markup/src/components/input.jsx
- packages/mask-markup/src/constructed-response.jsx
https://illuminate.atlassian.net/browse/PD-1395
https://illuminate.atlassian.net/browse/PD-1396
> fix(mask-markup): Separated input width and characters limit PD-1395 PD-1396

- packages/render-ui/src/preview-prompt.jsx
https://illuminate.atlassian.net/browse/PD-1456
> fix(render-ui): remove table border style PD-1456

- packages/editable-html/src/editor.jsx
2nd point in ticket: https://illuminate.atlassian.net/browse/PD-1459
> fix(editable-html): fix style for table rendering PD-1459

- packages/editable-html/src/plugins/table/__tests__/index.test.jsx
- packages/editable-html/src/plugins/table/index.jsx
feat(table): made sure focus is switched to first cell of the table when adding one [PD-1455]
> feat(table): made sure focus is switched to first cell of the table when adding one [PD-1455]

- packages/math-input/src/horizontal-keypad.jsx
- packages/math-input/src/keypad/index.jsx
- packages/math-input/src/keys/__tests__/utils.test.js
- packages/math-input/src/keys/constants.js
- packages/math-input/src/keys/geometry.js
- packages/math-input/src/keys/grades.js
- packages/math-input/src/keys/statistics.js
- packages/math-toolbar/src/editor-and-pad.jsx
- packages/math-toolbar/src/index.jsx
https://illuminate.atlassian.net/browse/PD-1442
https://illuminate.atlassian.net/browse/PD-1443
> feature(math-input, math-toolbar): add new math editors and clean up existing ones PD-1441, PD-1442, PD-1443

- packages/graphing/src/tools/line/component.jsx
- packages/graphing/src/tools/ray/component.jsx
- packages/graphing/src/tools/shared/point/arrow.jsx
- packages/graphing/src/tools/shared/point/base-point.jsx
- packages/graphing/src/utils.js
https://illuminate.atlassian.net/browse/PD-180
> fix(graphing): Adjusted the thickness of the shapes when the distance between lines is too small PD-180

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/math/index.jsx
- packages/editable-html/src/plugins/respArea/index.jsx
- packages/editable-html/src/plugins/toolbar/editor-and-toolbar.jsx
feat(editor): made sure cursor is visible before and after custom void elements [PD-1474]
> feat(editor): made sure cursor is visible before and after custom void elements [PD-1474]

- packages/graphing/src/__tests__/__snapshots__/graph.test.jsx.snap
- packages/graphing/src/axis/__tests__/__snapshots__/arrow.test.jsx.snap
- packages/graphing/src/axis/__tests__/axes.test.jsx
- packages/graphing/src/axis/arrow.jsx
- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/graph.jsx
- packages/graphing/src/tools/line/component.jsx
- packages/graphing/src/tools/ray/__tests__/__snapshots__/component.test.jsx.snap
- packages/graphing/src/tools/ray/component.jsx
- packages/graphing/src/utils.js
https://illuminate.atlassian.net/browse/PD-1509
> fix(graphing): Extended the range and domain axes and also the line and ray endings PD-1509

- packages/editable-html/src/plugins/math/__tests__/index.test.jsx
- packages/editable-html/src/plugins/math/index.jsx
https://illuminate.atlassian.net/browse/PD-1475
> feat(editor): made sure x<y is not removed from the math latex [PD-1475]

- packages/text-select/src/text-select.jsx
- packages/text-select/src/token-select/index.jsx
- packages/text-select/src/token-select/token.jsx
https://illuminate.atlassian.net/browse/PD-1526
> feat(select-text): add support for print PD-1526

- package.json
- packages/math-input/src/keys/grades.js
- yarn.lock
https://illuminate.atlassian.net/browse/PD-1578
> (math-editor): change operators order for item authoring math-editor

- packages/editable-html/src/plugins/table/__tests__/index.test.jsx
- packages/editable-html/src/plugins/table/index.jsx
fix(editor): made sure space is added after table even when there is a div wrapper [PD-1614]
> fix(editor): made sure space is added after table even when there is a div wrapper [PD-1614]

- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/utils.js
https://illuminate.atlassian.net/browse/PD-1596
> fix(graphing): Increased the calculation accuracy and adjusted range labels PD-1596

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/respArea/explicit-constructed-response/index.jsx
- packages/editable-html/src/plugins/respArea/index.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
chore(editor): fixed warnings for ECR [PD-1592]
https://illuminate.atlassian.net/browse/PD-1592
> chore(editor): fixed warnings for ECR [PD-1592]

- packages/charting/src/__tests__/utils.test.js
- packages/charting/src/utils.js
https://illuminate.atlassian.net/browse/PD-1645
> fix(charting): Added custom modulo function to work with decimals PD-1645

- packages/plot/src/root.jsx
https://illuminate.atlassian.net/browse/PD-1597
> fix(plot): Added HTML-encoded characters support PD-1597

- packages/mask-markup/src/mask.jsx
https://illuminate.atlassian.net/browse/PD-1651
> fix(mask): made sure display inherit is not messing up div blocks

- packages/graphing/src/tools/shared/point/arrow.jsx
- packages/graphing/src/tools/vector/__tests__/__snapshots__/component.test.jsx.snap
- packages/graphing/src/tools/vector/component.jsx
- packages/graphing/src/utils.js
https://illuminate.atlassian.net/browse/PD-1602
> fix(graphing): Adjusted vector arrow orientation angle and fixed rendering issue PD-1602

- packages/math-input/src/keypad/index.jsx
https://illuminate.atlassian.net/browse/PD-1669
> fix(math-input): PD-1669 handle latex with errors in keypad buttons

- packages/editable-html/src/plugins/list/index.jsx
fix(list): fixed list in list issues [PD-1229]
https://illuminate.atlassian.net/browse/PD-1229
> fix(list): fixed list in list issues [PD-1229]

- packages/config-ui/src/alert-dialog.jsx
- packages/config-ui/src/index.js
- packages/demo/pages/config-ui/index.js
https://illuminate.atlassian.net/browse/PD-1606
https://illuminate.atlassian.net/browse/PD-1608
alert dialog will also be used in multiple-choice
> feat: implemented an alert dialog

- packages/graphing/src/container/index.jsx
- packages/graphing/src/undo-redo.jsx
https://illuminate.atlassian.net/browse/PD-1608
> feat(graphing): updated store on model change PD-1608

- packages/math-toolbar/src/editor-and-pad.jsx
https://illuminate.atlassian.net/browse/PD-1786
> fix(math-toolbar): fix simple response gather PD-1786

- packages/graphing/src/__tests__/__snapshots__/grid.test.jsx.snap
- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/grid.jsx
https://illuminate.atlassian.net/browse/PD-1691
> feat(graphing): new design treatment for gridlines PD-1691

- packages/config-ui/src/index.js
- packages/config-ui/src/number-text-filed-custom.jsx
- packages/demo/pages/config-ui/numbers.js
https://illuminate.atlassian.net/browse/PD-1679
> feat: implemented custom number text field

- packages/graphing/src/grid-setup.jsx
- packages/graphing/src/index.js
https://illuminate.atlassian.net/browse/PD-1679
> feat: created a custom grid setup panel PD-1679

- packages/math-rendering/src/render-math.js
> (render-math): remove configuration that did not fixed the issue from PD-1635

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/characters/custom-popover.js
- packages/editable-html/src/plugins/characters/index.jsx
- packages/editable-html/src/plugins/characters/utils.js
- packages/editable-html/src/plugins/index.jsx
- packages/math-input/src/horizontal-keypad.jsx
- packages/math-input/src/keypad/index.jsx
- packages/math-input/src/keys/grades.js
- packages/math-toolbar/src/__tests__/__snapshots__/editor-and-pad.test.js.snap
- packages/math-toolbar/src/editor-and-pad.jsx
- packages/math-toolbar/src/index.jsx
- packages/rubric/src/__tests__/rubric.test.jsx
- packages/rubric/src/authoring.jsx
https://illuminate.atlassian.net/browse/PD-1461
https://illuminate.atlassian.net/browse/PD-1462
> feat(plugins): added special characters adding capabilities [PD-1462]

- packages/rubric/src/point-menu.jsx
https://illuminate.atlassian.net/browse/PD-1827
> fix: remove useless option PD-1827

- packages/editable-html/src/editor.jsx
https://illuminate.atlassian.net/browse/PD-1681
> feat(editable-html): Added characters limit support PD-1681

- packages/charting/src/__tests__/__snapshots__/axes.test.jsx.snap
- packages/charting/src/__tests__/__snapshots__/chart.test.jsx.snap
- packages/charting/src/axes.jsx
- packages/charting/src/chart.jsx
- revert charting; breaking change was not activated
> revert changes in charting axes and chart

- packages/graphing/src/graph-with-controls.jsx
https://illuminate.atlassian.net/browse/PD-1689
> feat(graphing): Added default value for current drawing tool PD-1689

- packages/charting/src/chart-setup.jsx
add constraints on max value for charting setup panel
https://illuminate.atlassian.net/browse/PD-1728
> feat(charting): add constraints on max value for charting setup panel PD-1728

- packages/graphing/src/graph-with-controls.jsx
- packages/graphing/src/graph.jsx
https://illuminate.atlassian.net/browse/PD-1693
> feat(graphing): added collapsible panel for graph toolbar PD-1693

- packages/config-ui/src/choice-configuration/index.jsx
- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/image/__tests__/__snapshots__/component.test.jsx.snap
- packages/editable-html/src/plugins/image/__tests__/__snapshots__/image-toolbar-logic.test.jsx.snap
- packages/editable-html/src/plugins/image/__tests__/__snapshots__/image-toolbar.test.jsx.snap
- packages/editable-html/src/plugins/image/__tests__/image-toolbar-logic.test.jsx
- packages/editable-html/src/plugins/image/component.jsx
- packages/editable-html/src/plugins/image/image-toolbar.jsx
- packages/editable-html/src/plugins/image/index.jsx
https://illuminate.atlassian.net/browse/PD-1801
> feat(editable-html): image resize functionality  PD-1801 

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/serialization.jsx
Tried several solutions but in the end I think this is the best one for our case.
https://illuminate.atlassian.net/browse/PD-581
> feat(editable-html): allow drop & paste images  PD-581

- babel.config.js
- package.json
- packages/editable-html/src/editor.jsx
Thank you, @lakatosandrei for your help.
> chore: added plugin-transform-runtime to support async await in pie-lib

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/respArea/index.jsx
- packages/editable-html/src/plugins/table/index.jsx
- packages/math-toolbar/src/editor-and-pad.jsx
Fixes various sentry issues.
[PD-1893](https://illuminate.atlassian.net/browse/PD-1893)
> fix(editable-html & math-toolbar): sentry

- packages/editable-html/src/plugins/image/image-toolbar.jsx
BREAKING CHANGE: Added new buttons in image toolbar.
The buttons control image horizontal alignment.
> feat(editable-html): add image alignment buttons

- packages/editable-html/package.json
- packages/math-input/package.json
- yarn.lock
https://illuminate.atlassian.net/browse/PD-1893
> fix: bump mathquill to 1.1.3

- packages/math-toolbar/src/editor-and-pad.jsx
https://illuminate.atlassian.net/browse/PD-1895
> fix(editable-html): remove language selector from math editor dropdown

- packages/editable-html/src/index.jsx
https://illuminate.atlassian.net/browse/PD-1893
> fix(editable-html): sanity checks

- packages/charting/src/axes.jsx
- packages/charting/src/chart.jsx
- packages/charting/src/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-1725
> feat(charting): select label when a new category is added PD-1725

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/toolbar/__tests__/__snapshots__/editor-and-toolbar.test.jsx.snap
- packages/editable-html/src/plugins/toolbar/editor-and-toolbar.jsx
- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/graph-with-controls.jsx
- packages/graphing/src/graph.jsx
- packages/graphing/src/grid-setup.jsx
- packages/graphing/src/labels.jsx
- packages/plot/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/plot/src/root.jsx
https://illuminate.atlassian.net/browse/PD-1719
> feat(graphing, plot): added pixel guide lines + ui improvements

- packages/render-ui/src/preview-prompt.jsx
https://illuminate.atlassian.net/browse/PD-1802
> fix: PD-1802 set style only to img parent

- packages/charting/src/chart-setup.jsx
https://illuminate.atlassian.net/browse/PD-1731
> feat(charting): add size constraints, configure acces for the client systems to control width and height visibility and constraints PD-1731

- packages/charting/src/__tests__/__snapshots__/axes.test.jsx.snap
- packages/charting/src/axes.jsx
https://illuminate.atlassian.net/browse/PD-1724
> feat(charting): add user confirmation alerts when interactive and editable props are set to false PD-1724 -b&C

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/characters/custom-popper.js
- packages/editable-html/src/plugins/characters/index.jsx
- packages/editable-html/src/plugins/characters/utils.js
- packages/editable-html/src/plugins/toolbar/default-toolbar.jsx
- packages/editable-html/src/plugins/toolbar/editor-and-toolbar.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
fix(plugins): can scroll on insert character toolbar, toolbar closes when not focused, not closing automatically on insert
[PD-1917](https://illuminate.atlassian.net/browse/PD-1917), [PD-1913](https://illuminate.atlassian.net/browse/PD-1913), [PD-1912](https://illuminate.atlassian.net/browse/PD-1912), [PD-1898](https://illuminate.atlassian.net/browse/PD-1898)
> fix(plugins): can scroll on insert character toolbar, toolbar closes when not focused, not closing automatically on insert

- packages/charting/src/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-29
> fix(charting): override grey background in IBX for chart disabled labels

- packages/graphing/src/__tests__/__snapshots__/graph.test.jsx.snap
- packages/graphing/src/graph.jsx
- packages/graphing/src/labels.jsx
https://illuminate.atlassian.net/browse/PD-1970
> fix(graphing): fix errors that appear in IBX in console

- packages/plot/src/grid-draggable.jsx
https://illuminate.atlassian.net/browse/PD-1989
> fix(plot): fix decimals arithmetic for drag value PD-1989

- packages/charting/src/__tests__/__snapshots__/chart.test.jsx.snap
- packages/charting/src/chart.jsx
- packages/plot/src/root.jsx
https://illuminate.atlassian.net/browse/PD-1732
> feat(charting): add pixel guides for Chart 1 PD-1732

- packages/math-input/src/keypad/index.jsx
- packages/math-toolbar/src/editor-and-pad.jsx
- packages/math-toolbar/src/math-preview.jsx
feedback from @andreeimiron on http://illuminate.atlassian.net/browse/PD-1521
> changes related to arrows PD-1521

- packages/charting/src/axes.jsx
https://illuminate.atlassian.net/browse/PD-2024
> fix(charting): fix category checkboxes  layout for iPads PD-2024

- packages/charting/src/utils.js
https://illuminate.atlassian.net/browse/PD-2025
> fix tickvalues: round with 4 decimals PD-2025

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/media/index.jsx
- packages/editable-html/src/plugins/media/media-dialog.js
https://illuminate.atlassian.net/browse/PD-23
New solution for PD-23. Upload to pie api logic not happening here anymore
> feat(editable-html): implement audio upload 

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/image/insert-image-handler.js
https://illuminate.atlassian.net/browse/PD-1960
> fix: fire add image method when copy-paste image is used

- packages/charting/src/chart.jsx
https://illuminate.atlassian.net/browse/PD-2086
> fix(charting): display math toolbar in define bottom label PD-2086

- packages/graphing/src/tools/shared/point/base-point.jsx
https://illuminate.atlassian.net/browse/PD-1947
> fix(graphing): increase draggable zone for graphing base point for better interaction with touchscreen devices

- packages/plot/src/label.jsx
- packages/plot/src/root.jsx
https://illuminate.atlassian.net/browse/PD-2131
> fix(charting): increase font size for axis labels and title PD-2131

- packages/config-ui/src/choice-configuration/index.jsx
- packages/editable-html/src/plugins/media/media-dialog.js
https://illuminate.atlassian.net/browse/PD-23
> fix(multiple-choice): add upload file option in choices PD-23

- packages/editable-html/src/plugins/toolbar/index.jsx
https://illuminate.atlassian.net/browse/PD-2129
> fix(editable-html): send autoWidth property to toolbar to fix PD-2129

- packages/editable-html/src/plugins/image/alt-dialog.jsx
https://illuminate.atlassian.net/browse/PD-2087
> fix(editable-html): increase helper text font size in alt dialog PD-2087

- packages/charting/src/chart-type.js
https://illuminate.atlassian.net/browse/PD-2166
> feat(charting): rename chart type labels

- packages/charting/src/__tests__/__snapshots__/axes.test.jsx.snap
- packages/charting/src/__tests__/__snapshots__/chart.test.jsx.snap
- packages/charting/src/axes.jsx
- packages/charting/src/chart.jsx
- packages/charting/src/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-1750
> feat(charting): UI/UX for validation PD-1750

- packages/drag/src/placeholder.jsx
BREAKING CHANGE: updated react-dnd and react-dnd-html5-backend versions The update was made in a previous commit, but breaking changes might occur so that's the role for this commit.
> feat: update react-dnd and react-dnd-html5-backend versions

- packages/config-ui/src/layout/layout-contents.jsx
- packages/config-ui/src/settings/panel.jsx
https://illuminate.atlassian.net/browse/PD-1998
> Feat/pd 1998/do not display an empty settings panel

- packages/config-ui/src/layout/layout-contents.jsx
https://illuminate.atlassian.net/browse/PD-2407 🤞🏻
> fix(config-ui): Settings Panel not showing up sometimes PD-2407

- packages/math-input/src/__tests__/__snapshots__/math-input-test.jsx.snap
- packages/math-input/src/keypad/__tests__/__snapshots__/index.test.jsx.snap
- packages/math-input/src/keypad/index.jsx
- packages/math-input/src/keys/comparison.js
- packages/math-input/src/keys/edit.js
- packages/math-input/src/keys/exponent.js
- packages/math-input/src/keys/fractions.js
- packages/math-input/src/keys/geometry.js
- packages/math-input/src/keys/log.js
- packages/math-input/src/keys/misc.js
- packages/math-input/src/keys/navigation.js
- packages/math-input/src/keys/operators.js
- packages/math-input/src/keys/statistics.js
- packages/math-input/src/keys/trigonometry.js
https://illuminate.atlassian.net/browse/PD-1872
> feat(math-input): add labels to math-operators and buttons that screen readers can use PD-1872

- packages/graphing/src/bg.jsx
https://illuminate.atlassian.net/browse/PD-1958
> fix(graphing): adjust clickable area for plotable shapes PD-1958

- packages/editable-html/src/editor.jsx
https://illuminate.atlassian.net/browse/PD-2144
> fix(editable-html): fix spellCheck functionality on mobile devices for extended-text-entry player PD-2144

- .circleci/config.yml
- packages/charting/src/bars/__tests__/__snapshots__/histogram.test.jsx.snap
- packages/charting/src/bars/common/bars.jsx
- packages/charting/src/bars/histogram.js
https://illuminate.atlassian.net/browse/PD-2034
> feat(charting): add colors for bars in histogram chart type PD-2034

- packages/graphing/src/tools/polygon/component.jsx
https://illuminate.atlassian.net/browse/PD-993
> fix(graphing): update model when polygon labels have changed PD-993

- packages/config-ui/src/layout/config-layout.jsx
- packages/config-ui/src/layout/layout-contents.jsx
https://illuminate.atlassian.net/browse/PD-1999
> feat(config-ui): added support to hide the settings pannel PD-1999

- packages/plot/src/label.jsx
https://illuminate.atlassian.net/browse/PD-2434
> fix(graphing): fix axis label rotation for ios devices PD-2434

- packages/text-select/src/token-select/token.jsx
https://illuminate.atlassian.net/browse/PD-1943
> fix(select-text): remove hover effect from tokens for touch devices PD-1943

- packages/graphing/src/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-2061
> fix(graphing): add background for objects labels PD-2061

- packages/drag/src/placeholder.jsx
https://illuminate.atlassian.net/browse/PD-2494
> fix(drag): fix choices arrangement in the drag placeholder PD-2494

- packages/drag/package.json
- packages/drag/src/placeholder.jsx
- packages/drag/src/with-drag-context.js
- yarn.lock
https://illuminate.atlassian.net/browse/PD-2495
> fix(drag): add support for dragging events on touch devices PD-2495

- packages/render-ui/src/preview-layout.jsx
https://illuminate.atlassian.net/browse/PD-2476
> feat(multiple-choice): add ARIA attributes PD-2476

- packages/charting/src/chart-setup.jsx
https://illuminate.atlassian.net/browse/PD-2625
> fix(charting): add sanity checks to data PD-2625

- packages/drag/src/placeholder.jsx
- packages/mask-markup/src/__tests__/__snapshots__/mask.test.js.snap
- packages/mask-markup/src/choices/choice.jsx
- packages/mask-markup/src/components/__tests__/__snapshots__/blank.test.js.snap
- packages/mask-markup/src/components/blank.jsx
- packages/mask-markup/src/mask.jsx
https://illuminate.atlassian.net/browse/PD-2607
> fix(drag-in-the-blank): improve drag choices for player on touch devices PD-2607

- packages/charting/src/__tests__/__snapshots__/chart.test.jsx.snap
- packages/charting/src/chart.jsx
https://illuminate.atlassian.net/browse/PD-2675
> fix(charting): fix style for chart boxes PD-2675

- packages/graphing/src/container/index.jsx
https://illuminate.atlassian.net/browse/PD-2677
> fix(graphing): fix undo and redo not working in gather PD-2677

- packages/graphing/src/tools/line/component.jsx
- packages/graphing/src/tools/ray/component.jsx
https://illuminate.atlassian.net/browse/PD-2653
> fix(graphing): fix arrow heads PD-2653

- packages/render-ui/src/preview-prompt.jsx
https://illuminate.atlassian.net/browse/PD-2699
> fix(multiple-choice): fix style for choice labels PD-2699

- packages/math-rendering/package.json
- packages/math-rendering/src/render-math.js
https://illuminate.atlassian.net/browse/PD-2474
> feat(math-rendering):upgrade mathjax version and enable accessibility mode PD-2474

- packages/charting/src/common/styles.js
https://illuminate.atlassian.net/browse/PD-2630
> feat(charting): mark up the category name in the student’s response as correct or incorrect with a rectangle

- packages/render-ui/src/preview-prompt.jsx
https://illuminate.atlassian.net/browse/PD-2720
> fix(multiple-choice): fix labels alignment PD-2720

- packages/graphing/src/tools/polygon/component.jsx
https://illuminate.atlassian.net/browse/PD-2753
> fix(graphing): remove shouldComponentUpdate from polygon PD-2753

- packages/render-ui/src/preview-prompt.jsx
https://illuminate.atlassian.net/browse/PD-2720
> fix(multiple-choice): fix vertical alignment within choice labels PD-2720

- packages/mask-markup/src/choices/choice.jsx
- packages/mask-markup/src/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-2770
> fix(drag-in-the-blank): prevent image interaction in choice - this is creating difficulties for drag choices on touch devices PD-2770

- packages/charting/src/chart-setup.jsx
https://illuminate.atlassian.net/browse/PD-2755
https://illuminate.atlassian.net/browse/PD-2625
> fix(charting): fix bad default state for chart data in author and player PD-2755, PD-2625

- packages/categorize/src/index.js
https://illuminate.atlassian.net/browse/PD-1982
> fix(categorize): add sanity check to fix PD-1982

- packages/charting/src/chart-setup.jsx
- packages/charting/src/chart.jsx
https://illuminate.atlassian.net/browse/PD-2774
> feat(charting): add authoring view settings for authorNewCategoryDefaults and studentNewCategoryDefaultLabel PD-2774

- packages/charting/src/__tests__/__snapshots__/chart.test.jsx.snap
- packages/charting/src/chart.jsx
https://illuminate.atlassian.net/browse/PD-2821
> fix(charting): provide mask id PD-2821

- packages/mask-markup/src/choices/choice.jsx
- packages/mask-markup/src/components/blank.jsx
- packages/mask-markup/src/mask.jsx
https://illuminate.atlassian.net/browse/PD-2066
> fix(mask-markup): update tokens design to support color contrast PD-2066

- jest.config.js
- packages/drag/package.json
- packages/drag/src/index.js
- packages/drag/src/with-drag-context.js
- yarn.lock
https://illuminate.atlassian.net/browse/PD-2722
> fix(drag): provide drag support for multiple devices PD-2722

- packages/demo/pages/editable-html.js
- packages/editable-html/src/__tests__/editor.test.jsx
- packages/editable-html/src/editor.jsx
- packages/editable-html/src/index.jsx
- packages/editable-html/src/plugins/math/__tests__/index.test.jsx
- packages/editable-html/src/plugins/math/index.jsx
- packages/math-rendering/package.json
- packages/math-rendering/src/__tests__/mml-to-latex.test.js
- packages/math-rendering/src/index.js
- packages/math-rendering/src/mml-to-latex.js
- packages/math-rendering/src/render-math.js
- yarn.lock
fix: added mathml editing support in editable-html, and mathml output PD-2150
> fix: added mathml editing support in editable-html, and mathml output PD-2150

- packages/drag/src/with-drag-context.js
> feat(drag): add context to dnd provider, context is needed when multiple dndProviders are used

- packages/drag/src/droppable-placeholder.jsx
https://illuminate.atlassian.net/browse/PD-3036
> (drag-in-the-blank): Prevent pop-up on long touch during item drag on touch devices PD-3036

- packages/drag/src/preview-component.jsx
https://illuminate.atlassian.net/browse/PD-3049
> (drag): Add and enhance preview component for match-list, placement-ordering and categorize drag functionality on touch devices PD-3049

- packages/config-ui/src/checkbox.jsx
https://illuminate.atlassian.net/browse/PD-2916
> feat(config-ui): add error support for checkboxes PD-2916

- packages/graphing/src/toggle-bar.jsx
- packages/graphing/src/undo-redo.jsx
https://illuminate.atlassian.net/browse/PD-2059
> fix(graphing): remove custom hover styling for action buttons PD-2059

- packages/drag/src/drag-in-the-blank-dp.jsx
- packages/drag/src/drag-type.js
- packages/drag/src/ica-dp.jsx
- packages/drag/src/index.js
- packages/drag/src/preview-component.jsx
- packages/mask-markup/src/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-3050
> fix(drag): Introduce droppablePlaceholder for ICA to enhance user interaction on touch devices PD-3050

- packages/graphing/src/bg.jsx
https://illuminate.atlassian.net/browse/PD-3005
> fix(graphing): adjust ploting position to match with the gridlines PD-3005

- packages/editable-html/src/serialization.jsx
fix: made sure div blocks are not present at the same level as paragraph ones PD-3051
> fix: made sure div blocks are not present at the same level as paragraph ones PD-3051

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/html/index.jsx
https://illuminate.atlassian.net/jira/software/c/projects/PD/issues/PD-2765?filter=myopenissues
> fix(editable-html): Disable HTML mode in player & retain html mode on alert dialog cancel PD-2765

- packages/demo/pages/editable-html.js
- packages/editable-html/src/plugins/math/index.jsx
- packages/math-rendering/package.json
- packages/math-rendering/src/__tests__/mml-to-latex.test.js
- packages/math-rendering/src/mml-to-latex.js
- yarn.lock
BREAKING CHANGE: updated mathml-to-latex version.
> fix: update mathml-to-latex version

- packages/charting/src/__tests__/__snapshots__/chart.test.jsx.snap
- packages/charting/src/bars/bar.js
- packages/charting/src/bars/common/__tests__/__snapshots__/bars.test.jsx.snap
- packages/charting/src/bars/common/bars.jsx
- packages/charting/src/chart.jsx
- packages/charting/src/common/drag-handle.jsx
- packages/charting/src/plot/common/__tests__/__snapshots__/plot.test.jsx.snap
- packages/charting/src/plot/common/plot.jsx
https://illuminate.atlassian.net/jira/software/c/projects/PD/issues/PD-2790?filter=myopenissues
> feat(charting): tweaks to design treatment of four chart types PD-2790

- packages/charting/src/chart-setup.jsx
- packages/charting/src/chart.jsx
https://illuminate.atlassian.net/browse/PD-3128
> fix(charting): limit number of categories in Define Initial Chart Attributes to 20 PD-3128

- packages/charting/src/common/drag-handle.jsx
https://illuminate.atlassian.net/browse/PD-2790
> fix(charting): add drop shadow to evaluate bars PD-2790

- packages/charting/src/chart.jsx
- packages/charting/src/common/drag-handle.jsx
https://illuminate.atlassian.net/browse/PD-3223
> fix(charting): address overlap of drag handle with category labels in charts PD-3223

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/toolbar/default-toolbar.jsx
https://illuminate.atlassian.net/browse/PD-2765
> fix(editable-html): hide DoneButton on active htmlMode, Prevent infinite loop in componentDidUpdate by refining isEdited state check PD-2765

- packages/editable-html/src/plugins/image/alt-dialog.jsx
https://illuminate.atlassian.net/browse/PD-3233
> fix(editable-html): Remove body overflow set by Material-UI and disable dialog scroll lock PD-3233

- packages/editable-html/src/editor.jsx
https://illuminate.atlassian.net/browse/PD-3221
> fix(editable-html): avoid using setState multiple times PD-3221

- packages/pie-toolbox/src/code/editable-html/editor.jsx
fix: made sure resizing is not messing up content PD-3298
> fix: made sure resizing is not messing up content PD-3298

- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/image/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/list/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/math/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/respArea/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/table/index.jsx
- packages/pie-toolbox/src/code/editable-html/test-serializer.js
fix: made sure that table is inserted near a block, so it is not removed by normalization PD-3299
> fix: made sure that table is inserted near a block, so it is not removed by normalization PD-3299

- packages/pie-toolbox/src/code/charting/common/drag-handle.jsx
- packages/pie-toolbox/src/code/charting/common/drag-icon.jsx
https://illuminate.atlassian.net/browse/PD-3271
> fix(charting): Fix: Update SVG style attribute to JSX format PD-3271

- packages/pie-toolbox/src/code/rubric/__tests__/__snapshots__/rubric.test.jsx.snap
- packages/pie-toolbox/src/code/rubric/authoring.jsx
https://illuminate.atlassian.net/browse/PD-3307
> feat(rubric): change max points logic PD-3307

- packages/pie-toolbox/src/code/text-select/token-select/token.jsx
https://illuminate.atlassian.net/browse/PD-2067
> fix(text-select): always display token text in black and update design PD-2067

- packages/pie-toolbox/src/code/charting/common/__tests__/__snapshots__/drag-handle.test.jsx.snap
- packages/pie-toolbox/src/code/charting/common/drag-handle.jsx
- packages/pie-toolbox/src/code/charting/common/drag-icon.jsx
https://illuminate.atlassian.net/browse/PD-3271
> fix(charting): ensure visibility of SVG drag icon PD-3271

- packages/pie-toolbox/src/code/graphing/__tests__/__snapshots__/grid.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/axis/axes.jsx
- packages/pie-toolbox/src/code/graphing/coordinates-label.jsx
- packages/pie-toolbox/src/code/graphing/graph-with-controls.jsx
- packages/pie-toolbox/src/code/graphing/grid.jsx
- packages/pie-toolbox/src/code/graphing/labels.jsx
- packages/pie-toolbox/src/code/graphing/mark-label.jsx
- packages/pie-toolbox/src/code/graphing/toggle-bar.jsx
- packages/pie-toolbox/src/code/graphing/tools/circle/bg-circle.jsx
- packages/pie-toolbox/src/code/graphing/tools/circle/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/polygon/line.jsx
- packages/pie-toolbox/src/code/graphing/tools/polygon/polygon.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/index.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/line-path.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/point/index.jsx
- packages/pie-toolbox/src/code/graphing/undo-redo.jsx
- packages/pie-toolbox/src/code/plot/root.jsx
https://illuminate.atlassian.net/browse/PD-3041
also fix charting issues: https://illuminate.atlassian.net/browse/PD-2068
> fix(graphing): use default colors for all color configurations PD-3041 PD-2068

- packages/pie-toolbox/src/code/editable-html/plugins/characters/index.jsx
fix: made sure inserting spanish characters does not cause an error PD-3300
> fix: made sure inserting spanish characters does not cause an error PD-3300

- packages/pie-toolbox/src/code/charting/chart.jsx
- packages/pie-toolbox/src/code/charting/tool-menu.jsx
- packages/pie-toolbox/src/code/plot/root.jsx
https://illuminate.atlassian.net/browse/PD-2068
> fix(charting): adjust color contrast and pixel gridlines position PD-2069

- packages/pie-toolbox/src/code/charting/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-2068
> fix(charting): use default color for non-editable category labels PD-2068

- packages/pie-toolbox/src/code/render-ui/preview-prompt.jsx
https://illuminate.atlassian.net/browse/PD-2060
> fix(render-ui): use black text for even table rows PD-2060

- packages/pie-toolbox/src/code/drag/preview-component.jsx
https://illuminate.atlassian.net/browse/PD-3352
> fix(drag): Implement zoom level detection and touch coordinate adjustments for drag preview in OT PD-3352

- packages/pie-toolbox/src/code/rubric/__tests__/rubric.test.jsx
- packages/pie-toolbox/src/code/rubric/authoring.jsx
https://illuminate.atlassian.net/browse/PD-3348
> fix(rubric): update maxPoints value model when changed PD-3348

- packages/pie-toolbox/src/code/graphing-utils/__tests__/utils.test.js
- packages/pie-toolbox/src/code/graphing-utils/index.js
- packages/pie-toolbox/src/code/graphing/__tests__/__snapshots__/graph-with-controls.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/tools/absolute/__tests__/component.test.jsx
- packages/pie-toolbox/src/code/graphing/tools/absolute/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/absolute/index.js
- packages/pie-toolbox/src/code/graphing/tools/exponential/__tests__/component.test.jsx
- packages/pie-toolbox/src/code/graphing/tools/exponential/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/exponential/index.js
- packages/pie-toolbox/src/code/graphing/tools/index.js
- packages/pie-toolbox/src/code/graphing/tools/parabola/__tests__/component.test.jsx
- packages/pie-toolbox/src/code/graphing/tools/parabola/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/index.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/with-root-edge.jsx
- packages/pie-toolbox/src/code/graphing/tools/sine/__tests__/component.test.jsx
- packages/pie-toolbox/src/code/graphing/tools/sine/component.jsx
- packages/pie-toolbox/src/code/graphing/utils.js
- packages/pie-toolbox/src/code/translator/en.js
- packages/pie-toolbox/src/code/translator/es.js
Added absolute value and exponential graph and functions as per below tickets and requirements.
[https://illuminate.atlassian.net/browse/SC-27396](https://illuminate.atlassian.net/browse/SC-27396)
[https://illuminate.atlassian.net/browse/SC-27398](https://illuminate.atlassian.net/browse/SC-27398)
> feat(graphing): Added absolute value and exponential graph and functions SC-27396 SC-27398

- packages/pie-toolbox/src/code/charting/line/common/__tests__/__snapshots__/drag-handle.test.jsx.snap
- packages/pie-toolbox/src/code/charting/line/common/drag-handle.jsx
- packages/pie-toolbox/src/code/charting/line/line-cross.js
https://illuminate.atlassian.net/browse/PD-3387
> fix(charting): add transparent circle handle for improved drag functionality on touch devices for line cross chart PD-3387

- packages/pie-toolbox/src/code/graphing/__tests__/__snapshots__/mark-label.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/__tests__/mark-label.test.jsx
- packages/pie-toolbox/src/code/graphing/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-3384
tested on ipad, online testing and local
> fix(graphing): Remove fontSize dependency from coordinate calculations PD-3384

- packages/pie-toolbox/src/code/charting/line/common/__tests__/__snapshots__/drag-handle.test.jsx.snap
- packages/pie-toolbox/src/code/charting/line/common/drag-handle.jsx
- packages/pie-toolbox/src/code/charting/line/line-dot.js
https://illuminate.atlassian.net/browse/PD-3383
> fix(charting): added larger transparent circle for drag handle in line dot chart to enhance touch device usability and accessibility PD-3383

- packages/pie-toolbox/src/code/graphing/graph.jsx
- packages/pie-toolbox/src/code/graphing/tools/circle/__tests__/component.test.jsx
- packages/pie-toolbox/src/code/graphing/tools/circle/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/point/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/polygon/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/__tests__/__snapshots__/index.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/tools/shared/line/__tests__/index.test.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/index.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/point/base-point.jsx
- packages/pie-toolbox/src/code/plot/grid-draggable.jsx
https://illuminate.atlassian.net/browse/PD-3392
> fix(graphing): made background shapes clickable PD-3392

- packages/pie-toolbox/src/code/graphing/graph.jsx
- packages/pie-toolbox/src/code/graphing/tools/circle/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/point/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/polygon/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/index.jsx
https://illuminate.atlassian.net/browse/PD-3392
> fix(graphing): disable click on background shapes in label model PD-3392

- packages/pie-toolbox/src/code/config-ui/number-text-field-custom.jsx
feat(config-ui): Modified NumberTextFieldCustom to disable Inc/Dec buttons | SC-28868
> feat(config-ui): Modified NumberTextFieldCustom to disable Inc/Dec button | SC-28868

- packages/pie-toolbox/src/code/config-ui/number-text-field-custom.jsx
- packages/pie-toolbox/src/code/config-ui/number-text-field.jsx
https://illuminate.atlassian.net/browse/PD-3509
> fix(config-ui): adjust the value with the new min and max props received PD-3509

- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
https://illuminate.atlassian.net/browse/PD-1870
> fix(math-rendering-accessible): Exclude MathJax-processed elements from placeholder creation PD-1870

- packages/pie-toolbox/src/code/math-input/keypad/index.jsx
- packages/pie-toolbox/src/code/math-input/keys/__tests__/utils.test.js
- packages/pie-toolbox/src/code/math-input/keys/grades.js
https://illuminate.atlassian.net/browse/PD-3549?focusedCommentId=1388850
> fix(math-input): fallback to grade set 8 if key is invalid PD-3549

- packages/pie-toolbox/src/code/mask-markup/components/correct-input.jsx
https://illuminate.atlassian.net/browse/PD-2461
> feat(explicit-constructed-response): add aria label for input items PD-2461

- packages/pie-toolbox/src/code/charting/mark-label.jsx
- packages/pie-toolbox/src/code/drag/preview-component.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/math/__tests__/index.test.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/math/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/respArea/drag-in-the-blank/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/choices/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
- packages/pie-toolbox/src/code/mask-markup/drag-in-the-blank.jsx
- packages/pie-toolbox/src/code/render-ui/__tests__/html-and-math.test.js
- packages/pie-toolbox/src/code/render-ui/collapsible/index.jsx
- packages/pie-toolbox/src/code/render-ui/html-and-math.js
https://illuminate.atlassian.net/browse/PD-1870
> feat: Replace math-rendering package with math-rendering-accessible-package for accessibility PD-1870

- packages/pie-toolbox/src/code/graphing-solution-set/graph-with-controls.jsx
Fixed issue with switching line type from solid to dashed and dashed to solid
> fix(graphing-solution-set): Fixed issue with switching line type

- packages/pie-toolbox/src/code/rubric/__tests__/__snapshots__/rubric.test.jsx.snap
- packages/pie-toolbox/src/code/rubric/authoring.jsx
https://illuminate.atlassian.net/browse/PD-3529
> feat: Add editable html configuration for rubric PD-3529

- packages/pie-toolbox/src/code/charting/line/common/drag-handle.jsx
https://illuminate.atlassian.net/browse/PD-3567
> fix(charting): use default colors for all configurations PD-3567

- packages/pie-toolbox/src/code/mask-markup/components/__tests__/__snapshots__/dropdown.test.js.snap
- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
- packages/pie-toolbox/src/code/mask-markup/inline-dropdown.jsx
https://illuminate.atlassian.net/browse/PD-2465
> feat(inline-dropdown): Implement screen reader-specific labels for inline dropdowns PD-2465

- packages/pie-toolbox/src/code/graphing-solution-set/__tests__/__snapshots__/graph-with-controls.test.jsx.snap
- packages/pie-toolbox/src/code/graphing-solution-set/__tests__/__snapshots__/graph.test.jsx.snap
- packages/pie-toolbox/src/code/graphing-solution-set/__tests__/__snapshots__/tool-menu.test.jsx.snap
- packages/pie-toolbox/src/code/graphing-solution-set/axis/axes.jsx
- packages/pie-toolbox/src/code/graphing-solution-set/graph-with-controls.jsx
- packages/pie-toolbox/src/code/graphing-solution-set/graph.jsx
- packages/pie-toolbox/src/code/graphing-solution-set/tool-menu.jsx
- packages/pie-toolbox/src/code/graphing-solution-set/tools/polygon/polygon.jsx
- packages/pie-toolbox/src/code/graphing-solution-set/tools/shared/line/index.jsx
- packages/pie-toolbox/src/code/graphing-solution-set/undo-redo.jsx
feat(graphing-solution-set): Modified HTML and CSS as per SC-30530 requirements.
[https://illuminate.atlassian.net/issues/SC-30530](https://illuminate.atlassian.net/issues/SC-30530)
> feat(graphing-solution-set): Modified HTML and CSS as per SC-30530 requirements.

- packages/pie-toolbox/src/code/graphing-solution-set/graph-with-controls.jsx
fix(graphing-solution-set): Fixed CSS padding for buttons
[https://illuminate.atlassian.net/issues/SC-30530](https://illuminate.atlassian.net/issues/SC-30530)
> fix(graphing-solution-set): Fixed CSS padding for buttons

- packages/pie-toolbox/src/code/charting/chart.jsx
- packages/pie-toolbox/src/code/plot/label.jsx
- packages/pie-toolbox/src/code/plot/root.jsx
1. Implemented axis label character limit settings for Charting item
https://illuminate.atlassian.net/browse/SC-30682
> feat(charting, plot): Charting Item Label Characters Limit SC-30682

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/editable-html/new-serialization.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/list/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/math/index.jsx
- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
fix: fixed some list wrapping and unwrapping issues PD-3493
> fix: fixed some list wrapping and unwrapping issues PD-3493

- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/toolbar.jsx
https://illuminate.atlassian.net/browse/PD-3494
> fix: added UNDO button [PD-3494]

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/editable-html/plugins/math/index.jsx
- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
https://illuminate.atlassian.net/browse/PD-3673
FIX:
https://github.com/pie-framework/pie-lib/assets/20281464/40e71799-6b26-49c2-b628-6b020d4245c9
> fix: when used in mmlOutput, we don't have to wait PD-3673

- packages/pie-toolbox/src/code/mask-markup/components/__tests__/__snapshots__/dropdown.test.js.snap
- packages/pie-toolbox/src/code/mask-markup/components/correct-input.jsx
- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
- packages/pie-toolbox/src/code/mask-markup/inline-dropdown.jsx
- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
https://illuminate.atlassian.net/browse/PD-2449
To make the dropdown component more accessible, the transition from using the Select component to a custom dropdown using a Button and Menu was implemented. This change provides a more explicit control over the accessibility features by customizing the interaction patterns and ensuring that all parts of the dropdown meet accessibility standards. Here's a breakdown of the steps taken and why they were necessary:
1. Explicit Control Over aria-* Attributes
In the new implementation, aria-haspopup, aria-expanded, and aria-activedescendant are directly managed by the Button component. This provides granular control over the accessibility attributes, ensuring they are updated dynamically and accurately represent the state of the dropdown. …
> feat(inline-dropdown): make the dropdown accessible PD-2449

- packages/pie-toolbox/src/code/drag/placeholder.jsx
https://illuminate.atlassian.net/browse/PD-3680
> fix(drag): add different style for categorize PD-3680

- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
https://illuminate.atlassian.net/browse/PD-3731
> fix(math-rendering-accessible): Specify parameters for element and render options when invoking the previous renderMath function PD-3731

- packages/pie-toolbox/src/code/charting/bars/common/bars.jsx
https://illuminate.atlassian.net/browse/PD-3621
> fix(charting): in bar chart handle disappears after drag

- packages/pie-toolbox/src/code/plot/label.jsx
- packages/pie-toolbox/src/code/plot/root.jsx
https://illuminate.atlassian.net/browse/PD-3620
> fix(charting) - bottom label is not moving with the content

- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
- packages/pie-toolbox/src/code/math-rendering/render-math.js
https://illuminate.atlassian.net/browse/PD-3731
> fix(math-rendering-accessible): Eliminate console logs added temporarily for debugging PD-3731

- packages/pie-toolbox/src/code/editable-html/plugins/characters/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/table/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/table/table-toolbar.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/toolbar.jsx
https://illuminate.atlassian.net/browse/PD-2127
> fix(editable-html): add special characters in table toolbar PD-2127

- packages/pie-toolbox/src/code/editable-html/editor.jsx
https://illuminate.atlassian.net/browse/PD-3709
> fix: add 1 000 000 max character limit on all html editors PD-3709

- packages/pie-toolbox/src/code/math-input/mq/__tests__/__snapshots__/input.test.jsx.snap
- packages/pie-toolbox/src/code/math-input/mq/input.jsx
https://illuminate.atlassian.net/browse/PD-3191
> fix(math-input): refresh content on click PD-3191

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/editable-html/plugins/customPlugin/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/image/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/math/index.jsx
https://illuminate.atlassian.net/browse/PD-3625
The errors I was getting is because jsx was returning children: []
> feat: migrate custom plugins PD-3625

- packages/pie-toolbox/src/code/correct-answer-toggle/index.jsx
https://illuminate.atlassian.net/browse/PD-3640
> fix(correct-answer-toggle): enchance with touch event the expander PD-3640

- packages/pie-toolbox/src/code/math-input/keys/__tests__/utils.test.js
- packages/pie-toolbox/src/code/math-input/keys/grades.js
https://illuminate.atlassian.net/browse/PD-3740
> fix(math-input): fixed wrong math editor for grade 1-2 PD-3740

- packages/pie-toolbox/src/code/editable-html/plugins/table/CustomTablePlugin.js
- packages/pie-toolbox/src/code/editable-html/plugins/table/index.jsx
https://illuminate.atlassian.net/browse/PD-2126
> fix: made sure deletion works properly in table editing [PD-2126]

- packages/pie-toolbox/src/code/feedback/index.js
- packages/pie-toolbox/src/feedback.js
https://illuminate.atlassian.net/browse/PD-1273
> fix(feedback): create new functions without using promise PD-1273

- packages/pie-toolbox/src/code/graphing/tools/circle/__tests__/__snapshots__/bg-circle.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/tools/circle/bg-circle.jsx
- packages/pie-toolbox/src/code/graphing/tools/circle/component.jsx
- packages/pie-toolbox/src/code/graphing/tools/polygon/__tests__/__snapshots__/line.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/tools/polygon/line.jsx
- packages/pie-toolbox/src/code/graphing/tools/polygon/polygon.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/__tests__/__snapshots__/line-path.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/tools/shared/line/index.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/line-path.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/point/__tests__/__snapshots__/arrow-point.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/tools/shared/point/__tests__/__snapshots__/base-point.test.jsx.snap
- packages/pie-toolbox/src/code/graphing/tools/shared/point/index.jsx
- packages/pie-toolbox/src/code/render-ui/color.js
https://illuminate.atlassian.net/browse/PD-3733
> feat: (graphing) View, points, edges, and arrows should all be black PD-3733

- packages/pie-toolbox/package.json
- yarn.lock
https://illuminate.atlassian.net/browse/PD-3180
> fix: upgrade mathml-to-latex version PD-3180

- packages/pie-toolbox/package.json
- packages/pie-toolbox/src/code/editable-html/plugins/list/index.jsx
- yarn.lock
fix: made sure lists work properly and are merged if one after another [PD-3391]
https://illuminate.atlassian.net/browse/PD-3391
> fix: made sure lists work properly and are merged if one after another [PD-3391]

- packages/pie-toolbox/src/code/editable-html/block-tags.js
- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/index.jsx
- packages/pie-toolbox/src/code/editable-html/serialization.jsx
https://illuminate.atlassian.net/browse/PD-3771
> feat: implemented blockquote button [PD-3771]

- packages/pie-toolbox/src/code/editable-html/__tests__/serialization.test.js
- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/index.jsx
- packages/pie-toolbox/src/code/editable-html/serialization.jsx
fix: made sure styles for h3 and blockquote are set properly
https://illuminate.atlassian.net/browse/PD-3771
https://illuminate.atlassian.net/browse/PD-3772
> fix: made sure styles for h3 and blockquote are set properly

- packages/pie-toolbox/src/code/editable-html/plugins/index.jsx
https://illuminate.atlassian.net/browse/PD-3775
> fix: implemented undo and redo buttons [PD-3775]

- packages/pie-toolbox/src/code/editable-html/plugins/index.jsx
https://illuminate.atlassian.net/browse/PD-3773
> feat: enter adds a new paragraph, regards of the block that is splitted [PD-3773]

- packages/pie-toolbox/src/code/editable-html/plugins/respArea/math-templated/index.jsx
https://illuminate.atlassian.net/browse/PD-3879
> fix(editable-html/math-templated): render math content PD-3879

- packages/pie-toolbox/src/code/editable-html/__tests__/editor.test.jsx
https://illuminate.atlassian.net/browse/PD-2455
https://illuminate.atlassian.net/browse/PD-3834
> test(editable-html): add tests for enhanced keyboard navigation and accessibility PD-2455

- packages/pie-toolbox/src/code/charting/common/drag-handle.jsx
https://illuminate.atlassian.net/browse/PD-3929
> fix(charting) disable chart objects to be moved in evaluate PD-3929

- packages/pie-toolbox/src/code/charting/__tests__/__snapshots__/axes.test.jsx.snap
- packages/pie-toolbox/src/code/charting/__tests__/__snapshots__/mark-label.test.jsx.snap
- packages/pie-toolbox/src/code/charting/axes.jsx
- packages/pie-toolbox/src/code/charting/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-3622
> feat: rotate inputs if they don't fit inside the space

- packages/pie-toolbox/src/code/math-input/keypad/index.jsx
https://illuminate.atlassian.net/browse/PD-3629
> fix: made sure special characters popup shows things on 4 rows [PD-3629]

- packages/pie-toolbox/src/code/graphing/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-3945
> fix(graphing): faded labels on touchscreen devices PD-3945

- packages/pie-toolbox/src/code/math-toolbar/editor-and-pad.jsx
https://illuminate.atlassian.net/browse/PD-3627
> fix(math-preview): ensure consistent styling for MathQuill elements within the editor and pad input container PD-3627

- packages/pie-toolbox/src/code/editable-html/plugins/characters/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/math/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/utils.js
https://illuminate.atlassian.net/browse/PD-3630
> fix(editable-html): revert changes PD-3630

- packages/pie-toolbox/src/code/plot/__tests__/__snapshots__/root.test.jsx.snap
- packages/pie-toolbox/src/code/plot/label.jsx
- packages/pie-toolbox/src/code/plot/root.jsx
- packages/pie-toolbox/src/code/plot/utils.js
https://illuminate.atlassian.net/browse/PD-3792
> Fix(graphing): Tighten up spacing in Graphing PD-3792

- packages/pie-toolbox/src/code/editable-html/plugins/media/media-dialog.js
https://illuminate.atlassian.net/browse/PD-3855
> fix: changed labeling for insert media [PD-3855]

- packages/pie-toolbox/src/code/mask-markup/components/__tests__/blank.test.js
https://illuminate.atlassian.net/browse/PD-3841
As discussed with @arimieandreea here: https://github.com/pie-framework/pie-lib/pull/1360#issuecomment-2269329173 we've decided to add unit tests to verify the behavior of newly added logic in updateDimensions and getRootDimensions.
> fix(mask-markup): Added unit tests for new logic updateDimensions and getRootDimensions PD-3841

- packages/pie-toolbox/src/code/drag/droppable-placeholder.jsx
- packages/pie-toolbox/src/code/drag/placeholder.jsx
https://illuminate.atlassian.net/browse/PD-3652
> fix(drag): moving styles for disabling long touch default events PD-3652

- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/DNA-22354
> fix(blank): Trigger updateDimensions in componentDidMount in case tokens are already placed to adjust blank dimensions DNA-22354

- packages/pie-toolbox/package.json
- yarn.lock
fix: made sure a working version of complexjs is used for elements [PD-4200]
> fix: made sure a working version of complexjs is used for elements [PD-4200]

- packages/pie-toolbox/src/code/text-select/token-select/index.jsx
https://illuminate.atlassian.net/browse/PD-4194
> fix(text-select): missing tokens were selectable PD-4194

- packages/pie-toolbox/src/code/editable-html/plugins/respArea/inline-dropdown/index.jsx
https://illuminate.atlassian.net/browse/PD-4201
> fix(inline-dropdown): adjust styling for response areas to be center aligned PD-4201

- packages/pie-toolbox/src/code/graphing/tools/polygon/line.jsx
- packages/pie-toolbox/src/code/graphing/tools/shared/line/line-path.jsx
https://illuminate.atlassian.net/browse/PD-4193
> fix(graphing): updated stroke width on polygon PD-4193

- packages/pie-toolbox/src/code/editable-html/plugins/image/__tests__/__snapshots__/image-toolbar.test.jsx.snap
- packages/pie-toolbox/src/code/editable-html/plugins/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/default-toolbar.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/toolbar-buttons.jsx
https://illuminate.atlassian.net/browse/PD-4018
> fix(editable-html): Added aria-labels for superscript, subscript, undo, and redo buttons in the toolbar PD-4018

- packages/pie-toolbox/src/code/mask-markup/components/__tests__/blank.test.js
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-4215
> fix(blank): for DITB adjust width by adding spacing after updateDimensions PD-4215

- packages/demo/pages/graphing/index.js
- packages/pie-toolbox/src/code/editable-html/__tests__/editor.test.jsx
- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/__tests__/__snapshots__/default-toolbar.test.jsx.snap
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/__tests__/__snapshots__/toolbar.test.jsx.snap
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/default-toolbar.jsx
- packages/pie-toolbox/src/code/plot/root.jsx
- packages/pie-toolbox/src/code/plot/utils.js
https://illuminate.atlassian.net/browse/PD-4209
> fix(graphing): fix title not updating properly and investigate labels PD-4209

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
https://illuminate.atlassian.net/browse/PD-4319
> feat: handle mml3 PD-4319

- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/respArea/explicit-constructed-response/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/editor-and-toolbar.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/toolbar.jsx
- packages/pie-toolbox/src/code/graphing-solution-set/labels.jsx
- packages/pie-toolbox/src/code/graphing/labels.jsx
- packages/pie-toolbox/src/code/mask-markup/constructed-response.jsx
- packages/pie-toolbox/src/code/mask-markup/serialization.js
- packages/pie-toolbox/src/code/plot/label.jsx
- packages/pie-toolbox/src/code/plot/root.jsx
https://illuminate.atlassian.net/browse/PD-4004
> Feat(ECR-respArea): option to include Spanish characters - respArea changed to EditableHtml PD-4004

- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/graphing-solution-set/labels.jsx
- packages/pie-toolbox/src/code/graphing/labels.jsx
- packages/pie-toolbox/src/code/mask-markup/constructed-response.jsx
- packages/pie-toolbox/src/code/plot/label.jsx
- packages/pie-toolbox/src/code/plot/root.jsx
https://illuminate.atlassian.net/browse/PD-4372
> Fix: resolve UI misalignment and unintended border PD-4372

- packages/pie-toolbox/src/code/mask-markup/choices/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/components/__tests__/blank.test.js
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-4393
> feat(mask-markup): add top and bottom padding for element PD-4393

- packages/pie-toolbox/src/code/mask-markup/components/__tests__/__snapshots__/blank.test.js.snap
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-4550
> feat(mask-markup): change target droppable area on hover PD-4550

- packages/pie-toolbox/src/code/editable-html/serialization.jsx
fix: made sure spans are handled as its one entity and also keeps attributes [PD-4165]
https://illuminate.atlassian.net/browse/PD-4165
> fix: made sure spans are handled as its one entity and also keeps attributes [PD-4165]

- packages/pie-toolbox/src/code/translator/en.js
- packages/pie-toolbox/src/code/translator/es.js
https://illuminate.atlassian.net/browse/PD-3843
https://illuminate.atlassian.net/browse/PD-4518
> feat(translator): add text for min/max selections PD-3843 PD-4518

- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-4588
> fix(blank): Added margin for response areas in student view PD-4588

- packages/pie-toolbox/src/code/editable-html/editor.jsx
https://illuminate.atlassian.net/browse/PD-4210
> fix(editable-html): Fix focus moving to start after typing Spanish or special characters PD-4210

- packages/pie-toolbox/src/code/render-ui/color.js
https://illuminate.atlassian.net/browse/PD-4555
> feat: defined focus colors in defaults for consistency and maintainability PD-4555

- packages/pie-toolbox/src/code/config-ui/layout/config-layout.jsx
https://illuminate.atlassian.net/browse/PD-4426
> fix(config-layout): updated sidePanelMinWidth default value to 1135px to accomodate the max width across all elements PD-4426

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/math-rendering/__tests__/render-math.test.js
- packages/pie-toolbox/src/code/math-rendering/render-math.js
fix: implemented math rendering accessible with the imported package [PD-4527]
> fix: implemented math rendering accessible with the imported package [PD-4527]

- packages/pie-toolbox/src/code/charting/mark-label.jsx
- packages/pie-toolbox/src/code/drag/preview-component.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/math/__tests__/index.test.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/math/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/respArea/drag-in-the-blank/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/choices/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
- packages/pie-toolbox/src/code/mask-markup/drag-in-the-blank.jsx
- packages/pie-toolbox/src/code/render-ui/__tests__/html-and-math.test.js
- packages/pie-toolbox/src/code/render-ui/collapsible/index.jsx
- packages/pie-toolbox/src/code/render-ui/html-and-math.js
- pslb/pslb.config.js
https://illuminate.atlassian.net/browse/PD-4527
> fix: replace mra package with mr, includes accessibility PD-4527

- packages/pie-toolbox/src/code/drag/with-drag-context.js
https://illuminate.atlassian.net/browse/PD-4689
> fix(drag): Fix touchpad interaction after touchscreen drag for image-cloze-association PD-4689

- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
- packages/pie-toolbox/src/code/mask-markup/mask.jsx
https://illuminate.atlassian.net/browse/PD-4704
https://illuminate.atlassian.net/browse/PD-4588
Before fix:
After fix:
> fix(blank): remove margins for chips in ditb PD-4704

- pslb/pslb.config.js
https://illuminate.atlassian.net/browse/PD-4527
> fix: Re-add @pie-lib/pie-toolbox/math-rendering-accessible to namespace imports for inclusion in the build

- packages/pie-toolbox/src/code/editable-html/plugins/respArea/math-templated/index.jsx
https://illuminate.atlassian.net/browse/PD-4589
> fix(math-templated): fix math rendering in math templated response areas PD-4589

- packages/pie-toolbox/src/code/editable-html/plugins/respArea/explicit-constructed-response/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/__tests__/__snapshots__/toolbar.test.jsx.snap
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/toolbar.jsx
- packages/pie-toolbox/src/code/mask-markup/constructed-response.jsx
https://illuminate.atlassian.net/browse/PD-4616
> fix(constructed-response): hide editable html toolbar in ECR if characters are not enabled PD-4616

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/math-rendering/render-math.js
https://illuminate.atlassian.net/browse/PD-4688
> fix: made sure math rendering is not delayed [PD-4688]

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/textAlign/icons/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/textAlign/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/default-toolbar.jsx
- packages/pie-toolbox/src/code/editable-html/serialization.jsx
https://illuminate.atlassian.net/browse/PD-3995
> feat: implemented textAlign capabilities [PD-3995]

- packages/pie-toolbox/src/code/editable-html/plugins/table/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/default-toolbar.jsx
https://illuminate.atlassian.net/browse/PD-4679
> feat(toolbar): Disable table and list buttons based on cursor context (PD-4679, PD-4678)

- packages/pie-toolbox/src/code/editable-html/__tests__/editor.test.jsx
- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/mask-markup/constructed-response.jsx
https://illuminate.atlassian.net/browse/PD-4618
> fix(ECR): adjusted width for constructed response areas PD-4618

- packages/pie-toolbox/src/code/editable-html/plugins/respArea/drag-in-the-blank/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/choices/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-4641
> fix(blank): fix font size for fractions in mathematical answer choices PD-4641

- packages/pie-toolbox/src/code/math-rendering/render-math.js
fix: made sure math rendering is not handling nodes that have been handled already [PD-4717]
https://illuminate.atlassian.net/browse/PD-4717
> fix: made sure math rendering is not handling nodes that have been handled already [PD-4717]

- packages/pie-toolbox/src/code/mask-markup/mask.jsx
https://illuminate.atlassian.net/browse/PD-4801
> fix(mask-markup): adjust padding for tables PD-4801

- packages/pie-toolbox/src/code/controller-utils/persistence.js
https://illuminate.atlassian.net/browse/PD-4820
> fix: Fix MC answer choice persistence by correctly retrieving shuffledValues PD-4820

- packages/pie-toolbox/src/code/controller-utils/persistence.js
https://illuminate.atlassian.net/browse/PD-4820
> fix: Ensure compatibility for shuffledValues retrieval PD-4820

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/editable-html/editor.jsx
https://illuminate.atlassian.net/browse/PD-4093
> fix: made sure that a paragraph sign is added after every block [PD-4093]

- packages/pie-toolbox/src/code/mask-markup/__tests__/__snapshots__/drag-in-the-blank.test.js.snap
- packages/pie-toolbox/src/code/mask-markup/drag-in-the-blank.jsx
- packages/pie-toolbox/src/code/mask-markup/mask.jsx
- packages/pie-toolbox/src/code/mask-markup/with-mask.jsx
https://illuminate.atlassian.net/browse/PD-4588 ( see comment )
https://illuminate.atlassian.net/browse/PD-4812
> fix(mask): fix spacing issues in DITB and ECR 

- packages/demo/pages/editable-html.js
- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/index.jsx
- packages/pie-toolbox/src/code/editable-html/serialization.jsx
https://illuminate.atlassian.net/browse/PD-4093
> feat: show paragraph symbol only after line breaks [PD-4093]

- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-4888
> fix: DITB Tokens cannot be dragged when touch and hold for some time into the response area PD-4888

- packages/pie-toolbox/src/code/render-ui/color.js
https://illuminate.atlassian.net/browse/PD-4555
> fix(multiple-choice): update focus outline color to meet WCAG 3:1 contrast ratio requirement PD-4555

- packages/pie-toolbox/src/code/editable-html/editor.jsx
https://illuminate.atlassian.net/browse/PD-5009
> PD-5009: fix: made sure spaces are shown between paragrahps if plugin is enabled

- packages/pie-toolbox/src/code/mask-markup/components/__tests__/__snapshots__/dropdown.test.js.snap
- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
https://illuminate.atlassian.net/browse/PD-5002
> feat(mask-markup): design update for inline-dropdown PD-5002

- packages/pie-toolbox/src/code/math-input/keypad/__tests__/__snapshots__/index.test.jsx.snap
- packages/pie-toolbox/src/code/math-input/keypad/index.jsx
- packages/pie-toolbox/src/code/math-input/mq/common-mq-styles.js
- packages/pie-toolbox/src/code/math-toolbar/editor-and-pad.jsx
- packages/pie-toolbox/src/code/math-toolbar/math-preview.jsx
Still in progress, creating draft for better visibility of progress
Key changes:
- refactored reused styles and moved them to external style file in order to not repeat code and have better maintainability
- fixed font for delete button in authoring side
_before (pits):_
_after:_
- added `!important` to italic parallel sign to fix in IBX
-  fixed font in player
_before (pits):_
_after:_
- fixed overarrow style issues
_before (pits):_
_after:_
- fixed line appearing for certain buttons in IBX:
> fix(math-input): fix math style issues in player, refactor common styles for better maintainability PD-4873

- packages/pie-toolbox/src/code/config-ui/__tests__/settings-panel.test.js
- packages/pie-toolbox/src/code/config-ui/settings/index.js
- packages/pie-toolbox/src/code/config-ui/settings/panel.jsx
- packages/pie-toolbox/src/code/config-ui/settings/toggle.jsx
https://illuminate.atlassian.net/browse/PD-4832
> fix(config-ui): add disable support for toggle PD-4832

- packages/pie-toolbox/src/code/text-select/index.js
- packages/pie-toolbox/src/text-select.js
https://illuminate.atlassian.net/browse/PD-363
https://illuminate.atlassian.net/browse/PD-653
> feat(select-text): export controls for pie-elements PD-363

- packages/pie-toolbox/src/code/text-select/index.js
- packages/pie-toolbox/src/text-select.js
Reverts pie-framework/pie-lib#1894
> Revert "feat(select-text): export controls for pie-elements PD-363"

- packages/pie-toolbox/src/code/charting/__tests__/__snapshots__/axes.test.jsx.snap
- packages/pie-toolbox/src/code/charting/axes.jsx
- packages/pie-toolbox/src/code/charting/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-5081
> feat(charting): limit input length to 20 for category labels PD-5081

- packages/pie-toolbox/src/code/mask-markup/components/__tests__/__snapshots__/dropdown.test.js.snap
- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
- packages/pie-toolbox/src/code/render-ui/color.js
https://illuminate.atlassian.net/browse/PD-4885 
Will look like this: 
https://github.com/user-attachments/assets/8739e7f2-165c-4f17-9384-9d6648374a28
> feat: dropdown menu changes PD-4885

- packages/pie-toolbox/src/code/render-ui/__tests__/html-and-math.test.js
- packages/pie-toolbox/src/code/render-ui/html-and-math.js
https://illuminate.atlassian.net/browse/PD-5097
> fix(categorize): remove renderMath to prevent excessive re-renders, refactor PD-5097

- packages/pie-toolbox/src/code/render-ui/color.js
- packages/pie-toolbox/src/code/text-select/legend.js
- packages/pie-toolbox/src/code/text-select/token-select/__tests__/__snapshots__/token.test.jsx.snap
- packages/pie-toolbox/src/code/text-select/token-select/token.jsx
- packages/pie-toolbox/src/code/translator/en.js
- packages/pie-toolbox/src/code/translator/es.js
https://illuminate.atlassian.net/browse/PD-5100
It will look like this:
> feat(text-select): ux changes - add new colors and new styles

- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
https://illuminate.atlassian.net/browse/PD-5131
> fix: ensure math renders correctly on hover preview and in dropdown choices PD-5131

- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
https://illuminate.atlassian.net/browse/PD-4885
- fixed math rendering width 
- fixed preview showing up when not selected
> fix(dropdown): improve dropdown rendering and state management PD-4885

- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/index.jsx
https://illuminate.atlassian.net/browse/PD-4918
> fix: made sure onChange is checking parsed html, debounced onResize [PD-4093]

- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
improved behavior explained here by George https://illuminate.atlassian.net/browse/PD-4579?focusedCommentId=2013136
> fix: improve keyboard navigation behaviour PD-4579

- packages/pie-toolbox/src/code/mask-markup/components/dropdown.jsx
https://illuminate.atlassian.net/browse/PD-4580
https://github.com/user-attachments/assets/f3e88c7a-d8a4-472f-a747-d9fd6860b251
> feat(mark-markup/dropdown): focus indicator for accessibility PD-4580
