- packages/config-ui/src/choice-configuration/__tests__/__snapshots__/index.test.jsx.snap
- packages/config-ui/src/choice-configuration/index.jsx
`noLabels` - no labels will be presented anywhere.
`useLetterOrdering` - instead of number ordering, choices will be listed alphabetically.
Also, the feedback input was positioned a little differently, more in-line with what the corespring version looks like.
Before:
After:
CC: @evaneus
> feature(choice-configuration): allow no label mode and adjust feedback input design

- packages/config-ui/package.json
Once merged, all other packages that depend on @pie-lib/config-ui will need to be updated.
Solves the keyboard input not working on number textfields. (specifically for extended-text-entry)
> feature(config-ui): version bump for material-ui to solve related bugs

- packages/editable-html/package.json
- packages/editable-html/src/plugins/index.jsx
- packages/editable-html/src/serialization.jsx
Solves https://github.com/pie-framework/pie-elements/issues/77.
All packages that depend on editable-html will need the version bump though in order to benefit from this plugin.
> feat(editable-html): added slate plugin for soft linebreaks

- packages/editable-html/src/plugins/toolbar/editor-and-toolbar.jsx
it seems like when an EditableHtml element is a top level children of an InputContainer it resizes until the maximum height on mouseOver and onMouseOut. This can be fixed either by having a wrapper for the EditableHtml component or by this PR.
> fix(editablehtml): fixed auto resizing

- packages/math-input/src/mq/static.jsx
BREAKING CHANGE: answer block mathquill mathfields now have a new id definition when declared
> feat(math-input): static math answer block support updated to formulaV2

- packages/math-toolbar/src/editor-and-pad.jsx
BREAKING CHANGE: response block addition now uses a different format
> fix(math-toolbar): response block addition switched to %response% from embeded custom element

- packages/demo/pages/graphing/demo-data.js
- packages/graphing/src/__tests__/__snapshots__/graph.test.jsx.snap
- packages/graphing/src/graph.jsx
- packages/graphing/src/tools/shared/line/index.jsx
- packages/plot/src/__tests__/__snapshots__/grid-draggable.test.jsx.snap
- packages/plot/src/__tests__/grid-draggable.test.jsx
- packages/plot/src/graph-props.js
- packages/plot/src/grid-draggable.jsx
- packages/plot/src/root.jsx
To get the correct x/y coordinates the drag logic needs a reference to
the root <g> node that contains all the elements.
> fix: fix bounded drag calculation

- packages/demo/pages/graphing/demo-data.js
- packages/demo/pages/graphing/index.js
- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/graph-with-controls.jsx
- packages/graphing/src/labels.jsx
- packages/graphing/src/tools/circle/__tests__/component.test.jsx
- packages/graphing/src/tools/circle/component.jsx
- packages/graphing/src/tools/circle/index.js
- packages/graphing/src/tools/line/__tests__/__snapshots__/component.test.jsx.snap
- packages/graphing/src/tools/line/component.jsx
- packages/graphing/src/tools/parabola/index.js
- packages/graphing/src/tools/point/component.jsx
- packages/graphing/src/tools/polygon/__tests__/__snapshots__/line.test.jsx.snap
- packages/graphing/src/tools/polygon/__tests__/__snapshots__/polygon.test.jsx.snap
- packages/graphing/src/tools/polygon/component.jsx
- packages/graphing/src/tools/polygon/line.jsx
- packages/graphing/src/tools/polygon/polygon.jsx
- packages/graphing/src/tools/ray/__tests__/__snapshots__/component.test.jsx.snap
- packages/graphing/src/tools/ray/component.jsx
- packages/graphing/src/tools/segment/component.jsx
- packages/graphing/src/tools/shared/__tests__/__snapshots__/arrow-head.test.jsx.snap
- packages/graphing/src/tools/shared/arrow-head.jsx
- packages/graphing/src/tools/shared/line/__tests__/__snapshots__/line-path.test.jsx.snap
- packages/graphing/src/tools/shared/line/index.jsx
- packages/graphing/src/tools/shared/line/line-path.jsx
- packages/graphing/src/tools/shared/line/with-root-edge.jsx
- packages/graphing/src/tools/shared/point/arrow.jsx
- packages/graphing/src/tools/sine/index.js
- packages/graphing/src/tools/vector/component.jsx
- backgroundMarks were not displaying anymore proper colours for disabled, correct and incorrect. 
- Circle was crashing. 
- Don't allow user to drag pointB over pointA or pointA over pointB for all the elements but polygon.
- for numbers greater than 99, don't let tick labels cut the y axis
- stop app crashing when adding labels
- added a way to determine which tools should be displayed in tool menu. We need this because in pie-element the author can select some background marks, and when he selects the tools that should be displayed to the student, if he deselects a tool that there's already a background mark for, the app will crash (for example, author adds circle as background mark, but when he defines correct answer, he selects not to display circle tool for the student. In that …
> Bug fixes.

- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/graph-with-controls.jsx
The toolbar renders outside the graph box.
Axis labels don't render markup, so HTML tags are shown.
> Graphing reported issues

- packages/editable-html/src/index.jsx
- packages/editable-html/src/parse-html.js
The original issue is reported [here](https://app.clubhouse.io/keydatasystems/story/1792/inline-math-degree-symbol-generates-undefined-control-sequence-error-when-rendering).
A very similar issue occurs for `≈` operator, and might occur for others too, but haven't tested for all symbols yet.
Not sure if this is the right approach to fix it, but let me know what you think.
> fix: render degrees as expected

- packages/correct-answer-toggle/src/index.jsx
Issue reported [here](https://app.clubhouse.io/keydatasystems/story/3177/ibx-item-authoring-hide-correct-answer-icon-not-displaying-properly).
Is there any trigger for pushes that auto-indents the code? The lines added seems to be auto-indented. 
Before pushing I had:
```
<CSSTransition 
timeout={400} 
in={toggled} 
exit={!toggled} 
classNames={classes}
>
```
and after the code changed to
```
<CSSTransition timeout={400} in={toggled} exit={!toggled} classNames={classes}>
```
> Fix auto-hide correct answer icon 

- packages/editable-html/src/index.jsx
This seems innocuous and the tests pass, but Ed should verify.
> fix: don't format to html / emit in constructor

- packages/math-toolbar/src/editor-and-pad.jsx
Unfortunately, not something that I can test for - this was breaking 100% in case of noDecimal model for math-inline in initial render. (We need the onChange right after mounting the editor, technical limitation)
> fix(math-toolbar): un-initialized input problem fix in case of no decimal flow

- packages/controller-utils/src/__tests__/persistence.test.js
- packages/controller-utils/src/index.js
- packages/controller-utils/src/persistence.js
Reqs described [here](https://app.clubhouse.io/keydatasystems/story/131/config-ui-support-shuffle-choices).
After approval & merge will the version of `@pie-lib/controller-utils` be `0.1.3`? The latest is `v0.1.2`. I need to know to which version to bump, thinking at the interactions that uses `getShuffledChoices` method.
> feat: implement a shuffle/persistence reusable method

- packages/mask-markup/src/choices/choice.jsx
- packages/mask-markup/src/components/blank.jsx
In IBX OT, Drag in the Blank items have draggable tokens with text that is too small to comfortably read: prevent using a fontSize of 0.8125rem (material-ui) and override that css property.
> fix: small text for drag-in-the-blank

- packages/math-input/src/keypad/index.jsx
Math editor in OT has button labels that are very small and impact legibility and usability (don't use rem to determine font size)
> fix: 6264:

- packages/editable-html/src/plugins/image/__tests__/__snapshots__/component.test.jsx.snap
- packages/editable-html/src/plugins/image/component.jsx
- packages/editable-html/src/plugins/image/index.jsx
IBX rendering of images in MC answer choices stretches them vertically (or squeezes them horizontally), causing distortion that invalidates some items.
> fix: 5590: Force the image to keep its shape

- packages/math-input/src/keys/__tests__/utils.test.js
- packages/math-input/src/keys/grades.js
(In OT, a math editor for an Equation Response item is missing a critical button as well as many other expected buttons)
> fix: 6287: Setting equation editor as a string (eg: '6') works as well

- packages/graphing/src/__tests__/utils.test.js
- packages/graphing/src/axis/__tests__/__snapshots__/axes.test.jsx.snap
- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/utils.js
- 5349: For Graphing items, move the origin label
- 5736: In Graphing, the horizontal alignment of multi-digit numeric labels for the x-axis is off
- 4155: Graphing item that wasn't supposed to have an x-axis or a y-axis still has them.
> fix: ch5349, ch5736 & ch4155:

- packages/math-input/src/keypad/index.jsx
The "pink" background-color set on .mq-empty is overwritten by mathquill.css with "transparent". Added "important" to prevent this.
> fix: PD-155: In IBX and Sandbox math editors, the pink highlighting used on certain buttons is missing

- packages/math-input/src/keypad/index.jsx
In Item Preview specifically, in IBX only, the math editor radical button and the "squared" button are not correctly labeled
> fix: PD-158: fixed scaled items

- packages/categorize/src/__tests__/index.test.js
- packages/categorize/src/index.js
"Best scenario" for categorise was not calculated properly.
One Alternate Response has to be treated as an entire possible correct response, not alternate for each category individually.
If one item has alternates, no partial scoring applied => if no response is entirely correct, score will be 0.
If there are no alternates, partialScoring can be applied.
This one needs a release (new version) to be used in pie-ui and pie-elements.
> fix: PD-45: The best scenario is not properly found. (If alternates defined => dychotomous)

- packages/editable-html/src/__tests__/serialization.test.js
- packages/editable-html/src/serialization.jsx
- packages/mask-markup/src/__tests__/__snapshots__/mask.test.js.snap
- packages/mask-markup/src/__tests__/mask.test.js
- packages/mask-markup/src/__tests__/serialization.test.js
- packages/mask-markup/src/mask.jsx
- packages/mask-markup/src/serialization.js
PD-338: feat(serialization): made sure line breaks are handled and placed where they need to be
PD-800: feat(serialization): made sure the max iteration is enough to iterate over the html
PD-800: feat(serialization): made sure em tags are rendered in the mask-markup elements
> PD-338: feat(serialization): made sure line breaks are handled and placed where they need to be

- packages/config-ui/src/settings/panel.jsx
Some interactions were simply reliant on the choices array being present. This way at least it won't break the interaction down entirely if it's missing. `3eb3a4ac-eccb-11ea-a4dd-b27091dc957b` breaks it entirely.
> fix(config-ui): fix choices map null check - PD-879

- packages/mask-markup/src/components/dropdown.jsx
For the inline-dropdown element, render new choices as html in the player side, not as string.
https://illuminate.atlassian.net/secure/RapidBoard.jspa?rapidView=439&projectKey=PD&modal=detail&selectedIssue=PD-887&assignee=601120f0c8c36c0069681445
> fix(inline-dropdown): render item as html - PD-887

- packages/math-input/src/mq/input.jsx
https://illuminate.atlassian.net/browse/PD-655
I don't think this is the best solution, but couldn't find a better one.
The issue is that the field gets to be focused before it has the proper handlers set.
(I've tried to find a callback/a way to figure out when handlers are ready without success).
The 0 timeout and combination of steps does the trick.
Notes: having only focus inside the timeout (without the focus - blur - focus steps) does not work.
> fix: In some situations, math editors will not accept keyboard entry  PD-655.

- packages/graphing/src/tools/shared/point/arrow.jsx
- packages/graphing/src/tools/vector/component.jsx
- packages/graphing/src/utils.js
Rollback #283 since that fix works for only 4 use cases. The fix for initial issue should apply for any angle of the arrow.
> fix(graphing): ROLLBACK - fix arrow positioning PD-495

- packages/mask-markup/src/components/__tests__/__snapshots__/blank.test.js.snap
- packages/mask-markup/src/components/blank.jsx
It's a hacky fix, but I've already spend some time on it. Setting `height: auto` will make some of the chip items to not be draggable anymore.
[PD-1034](https://illuminate.atlassian.net/browse/PD-1034)
> fix(mask-markup): fix dragging issue by overwriting material ui chip height

- packages/charting/src/axes.jsx
- packages/charting/src/tool-menu.jsx
- packages/graphing/src/axis/axes.jsx
- packages/graphing/src/graph-with-controls.jsx
- packages/graphing/src/labels.jsx
- packages/graphing/src/toggle-bar.jsx
- packages/graphing/src/undo-redo.jsx
- packages/plot/src/root.jsx
Fix for Charting and Graphing, in IBX and OT, x- and y-axis labels and y-axis numeric labels are too small 
https://illuminate.atlassian.net/browse/PD-533
> Fix for Charting and Graphing, in IBX and OT, labels are too small - PD-533

- packages/mask-markup/src/components/blank.jsx
In DITB, when a label is dragged on another label, the old label should be hidden, but when we have images, this is not happening.
> fix(mask-markup): Fixed labels overlapping

- packages/math-input/src/mq/input.jsx
PD-655: feat(input): on key press we check if the input handlers are set on the field and if not, we're setting them by refocusing
> PD-655: feat(input): on key press we check if the input handlers are set on the field and if not, we're setting them by refocusing

- packages/editable-html/src/editor.jsx
fix(editor): made sure that if the editor loses focus, the onBlur function is called no matter what [PD-1126]
> fix(editor): made sure that if the editor loses focus, the onBlur function is called no matter what [PD-1126]

- packages/editable-html/src/editor.jsx
fix(editor): made sure that if the editor loses focus, the onBlur function is called only if the focus is still not inside the dom element [PD-1126]
> fix(editor): made sure that if the editor loses focus, the onBlur function is called only if the focus is still not inside the dom element [PD-1126]

- packages/editable-html/src/editor.jsx
- packages/editable-html/src/plugins/toolbar/editor-and-toolbar.jsx
- packages/editable-html/src/plugins/toolbar/toolbar.jsx
fix(editor): used dom refs in order to check if the editor is still in focus [PD-1126]
> fix(editor): used dom refs in order to check if the editor is still in focus [PD-1126]

- packages/mask-markup/src/choices/choice.jsx
- packages/mask-markup/src/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-1351
image tokens are now centered and don't cover top border:
> fix(mask-markup): fix style for drag-in-the-blank image tokens PD-1351

- packages/math-rendering/src/render-math.js
https://illuminate.atlassian.net/browse/PD-1384
before:
after:
> fix(math-rendering): fix line spacing for mathjax mspace PD-1384

- packages/editable-html/src/plugins/media/media-dialog.js
https://illuminate.atlassian.net/browse/PD-1488
> fix(editable-html): Insert button from video/audio modal can't be pressed if the URL is empty PD-1488

- packages/mask-markup/src/mask.jsx
- packages/mask-markup/src/serialization.js
Render mathml in a `dangerouslySetInnerHTML` property.
It seems `open` mathml property is being overwritten by React. Maybe it's worth to report this issue on React repo. 
Sources:
* https://github.com/facebook/react/issues/9320
* https://github.com/remarkablemark/html-react-parser/issues/301
* https://stackoverflow.com/questions/51319758/react-16-html-attributes-with-mathml-tags
Ticket: https://illuminate.atlassian.net/browse/PD-397
> fix(mask-markup): render mathml correctly

- packages/mask-markup/src/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-1652
@sergiulucaci please look at this, I re-added  `height: auto` (added initially by @PatriciaRomaniuc)  which you removed, this fixes the height when the text is too long, the blank adjust to the content
> fix(blank): made sure height is auto to adapt to content, until it is calculated [PD-1652]

- packages/charting/src/__tests__/__snapshots__/axes.test.jsx.snap
- packages/charting/src/__tests__/__snapshots__/chart.test.jsx.snap
- packages/charting/src/axes.jsx
- packages/charting/src/chart.jsx
BREAKING CHANGE: The editCategoryEnabled propery has been removed
- add “Student can edit name” checkboxes on Chart 1
- remove editCategoryEnabled property checkbox and usage
- editable remains a property of the root-level data element, controlled by “Student can edit name” checkboxes
- update snapshots
> feat(charting): remove editCategoryEnabled property checkbox and usage

- packages/editable-html/src/editor.jsx
- packages/math-input/src/keypad/index.jsx
- packages/math-rendering/src/mstack/chtml.js
- packages/math-toolbar/src/editor-and-pad.jsx
Tackles https://illuminate.atlassian.net/browse/PD-1521.
We're overwriting mathquill to be inline with mathjax. 
We're not covering everything but we just wanna fix the bad looking math rendering (you can check ticket's comments). 
I'm not so confident about the changes tbh, that's why I'm asking @andreeapescar & @andreeimiron to test & report what looks odd.
Thanks!
> feat(editable-html & math-toolbar & math-rendering) Overwrite mathquill font

- packages/editable-html/package.json
- packages/editable-html/src/editor.jsx
https://illuminate.atlassian.net/browse/PD-1899
Because in this slate version returning true or calling `next()` in `onPaste` method Slate does not execute its own event handler, in case type of paste transfer is not an image we use the default `onPaste` code from slate, which can be found under slate-react/lib/slate-react.es.js line 3221 (slate-react@0.14.3).
> fix(editable-html): fix paste text PD-1899

- packages/render-ui/src/preview-prompt.jsx
[PD-2037](https://illuminate.atlassian.net/browse/PD-2037)
Layout bug affecting ECR items that include an image in the stem
> fix: revert PD-1802 work because it is causing big issues PD-2037

- packages/editable-html/src/plugins/media/index.jsx
- packages/editable-html/src/plugins/media/media-dialog.js
- packages/editable-html/src/plugins/media/media-toolbar.jsx
https://illuminate.atlassian.net/browse/PD-23
Please note that a "Loading..." will be shown until the file is uploaded by the client. Not 100% it is good to show it - it will be sticky in testing environments - maybe we can check with George. 
For now we hide "Edit Settings" for uploaded sound in editable-html and show "Remove" option only. This can be a nice task if it's wanted - the developer will have to make some changes in the code to have a consistent logic though (url vs uploaded sound). 
Progress can be implemented as well.
> feat: UI improvements and bit of cleanup for PD-23-updated

- packages/config-ui/src/layout/__tests__/__snapshots__/config.layout.test.jsx.snap
- packages/config-ui/src/layout/config-layout.jsx
https://illuminate.atlassian.net/browse/PD-2462
https://illuminate.atlassian.net/browse/PD-2463
> fix(config-ui): make sure that the bounds for the ConfigLayout are calculated before rendering the elements on iPads PD-2462 PD-2463 

- packages/config-ui/src/layout/config-layout.jsx
- packages/config-ui/src/layout/layout-contents.jsx
Added the following classnames:
**main-container** - for the main wrapper
**design-container** - for the design wrapper
**settings-container** - for the settings wrapper
**settings-box** - for the settings wrapper child (available when design and settings containers are displayed at the same time on the screen)
> feat(config-ui): added default classnames for main components

- packages/demo/pages/translator/index.js
- packages/translator/src/index.js
BREAKING CHANGE: The translator is now inside the returned object, not the object itself.
> feat: expanded translator by exposing languageOptions PD-2795

- packages/drag/package.json
- packages/drag/src/preview-component.jsx
- packages/drag/src/with-drag-context.js
- packages/mask-markup/src/components/blank.jsx
- yarn.lock
https://illuminate.atlassian.net/browse/PD-2991
https://illuminate.atlassian.net/browse/PD-2992
https://illuminate.atlassian.net/browse/PD-3036
In version 2.2.1 of @pie-lib/drag, I introduced 'react-dnd-multi-backend'. However, this inadvertently led to an 'Invisible drag' issue on touch devices, due to the absence of a preview for the dragged element. To address this, I've incorporated a preview component in this Pull Request that aligns with the TouchBackend, effectively emulating the existing preview functionality of the HTML5Backend. This update aims to provide a consistent and intuitive drag-and-drop experience across various devices and interaction modes.
The drag functionality we currently have utilizes different 'choices' or 'components' for each element, necessitating unique …
> (drag): add preview for drag items on touch screen PD-2991, PD-2992, PD-3036

- packages/editable-html/src/__tests__/serialization.test.js
- packages/editable-html/src/index.jsx
- packages/editable-html/src/serialization.jsx
fix: made sure multiple nodes are wrapped in a block, in order for slate to handle it properly PD-3051
> fix: made sure multiple nodes are wrapped in a block, in order for slate to handle it properly PD-3051

- packages/pie-toolbox/src/code/charting/__tests__/__snapshots__/axes.test.jsx.snap
- packages/pie-toolbox/src/code/charting/__tests__/__snapshots__/chart.test.jsx.snap
- packages/pie-toolbox/src/code/config-ui/alert-dialog.jsx
- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/html/index.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/default-toolbar.jsx
This pull request introduces the following features and improvements:
Preview Dialog for HTML Edits: A new functionality has been implemented where users are presented with a dialog box upon clicking a green 'Done' button. This dialog showcases a preview of the edited HTML, allowing users to either accept or reject the changes. This feature facilitates real-time review and validation before saving any edits made to the HTML.
Enhanced Exit Mechanism: The existing 'exit html' button and its associated alert dialog have been refactored. Users now have a clearer choice post-editing: they can opt to continue editing the HTML or they can revert all changes and return to the WYSIWYG (What You See Is What You Get) mode. This change enhances user control and decision-making regarding their HTML …
> fix(editable-html): Add preview dialog for HTML edits and improve exit workflow PD-2765

- packages/pie-toolbox/src/code/charting/common/drag-handle.jsx
- packages/pie-toolbox/src/code/charting/common/drag-icon.jsx
> fix(charting): Fix SVG visibility by overriding global overflow rule in pie-components PD-3271

- packages/pie-toolbox/src/code/charting/__tests__/__snapshots__/chart.test.jsx.snap
- packages/pie-toolbox/src/code/charting/axes.jsx
- packages/pie-toolbox/src/code/charting/chart.jsx
- packages/pie-toolbox/src/code/charting/common/drag-handle.jsx
- packages/pie-toolbox/src/code/charting/common/drag-icon.jsx
https://illuminate.atlassian.net/jira/software/c/projects/PD/issues/PD-3130?filter=myopenissues
Refactor autoFocus handling for category addition
- Shift autoFocus state management from category data to component state.
- Implement conditional autoFocus logic in child components to ensure focus is applied only once after adding a new category.
- Remove redundant autoFocus properties from category data to prevent unintended focusing on subsequent renders.
- Enhance maintainability and prevent unwanted autofocus behavior.
This change addresses the issue where the previous implementation of embedding autoFocus within category data led to repeated and unwanted autofocus on multiple renders.
> fix(charting): Refactor autoFocus handling for category addition PD-3130

- packages/pie-toolbox/src/code/math-input/mq/input.jsx
https://illuminate.atlassian.net/browse/PD-3296
> fix(math-input): prevent newLine insertion on Enter in math editor PD-3296

- packages/pie-toolbox/src/code/charting/bars/common/__tests__/__snapshots__/bars.test.jsx.snap
- packages/pie-toolbox/src/code/charting/bars/common/bars.jsx
- packages/pie-toolbox/src/code/charting/common/drag-icon.jsx
- packages/pie-toolbox/src/code/charting/plot/common/__tests__/__snapshots__/plot.test.jsx.snap
- packages/pie-toolbox/src/code/charting/plot/common/plot.jsx
https://illuminate.atlassian.net/browse/PD-3366
Fix involved:
- Removing SVG filters that impaired visibility on iPads.
- Adding explicit 'height' and 'viewBox' attributes to SVGs for better dimension control.
- Replacing hover events with touch events specifically for iPad devices to enhance usability.
This ensures a consistent and interactive experience across various devices.
> fix(charting): enable Category Drag Handle icon on iPad PD-3366

- packages/pie-toolbox/src/code/charting/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-3367
Implemented a fix for the positioning of labels containing mathematical expressions by setting their position to 'fixed'. This adjustment specifically addresses a layout issue on various devices, including iPads, where these labels were not correctly aligned within the chart component. By applying 'position: fixed', these math-containing labels are now consistently positioned across different browsers and devices.
Before fix: 
After fix:
> fix(charting): Fix positioning for math-containing labels with fixed positioning addressing a layout issue on various devices, including iPads PD-3367

- packages/pie-toolbox/src/code/charting/common/drag-handle.jsx
https://illuminate.atlassian.net/browse/PD-3501
- removed height since it was not doing anything
- changed circle into ellipse (oval shape) because we needed a larger drag area
added a sheer background in these screenshots just to show how the transparent background area is situated with the new changes:
> fix(charting): change drag handle area into ellipse PD-3501

- packages/pie-toolbox/src/graphing-utils.js
Fixed missing imports in graphing-utils.js | SC-28500
> fix(graphing-utils): Fixed missing imports in graphing-utils.js

- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
Behaviour explanation: 
MathJax can sometimes add nested mjx-container elements during content reprocessing. This behavior typically happens in dynamic web applications, especially in frameworks like React or Vue, where content can be updated or re-rendered based on user interactions or state changes.
When MathJax processes an element containing mathematical notation, it wraps the content in an mjx-container to handle layout and rendering. If the same element undergoes processing by MathJax again (for instance, after being dynamically updated or when a component containing it re-renders), MathJax may not recognize that it has already processed this content. As a result, it wraps the content in another mjx-container, leading to nested containers.
This nesting can lead to issues such as: …
> fix(math-rendering-accessible): add sanity checks PD-1870, add function to clean up excess mjx-container elements PD-3564

- packages/pie-toolbox/src/code/mask-markup/with-mask.jsx
https://illuminate.atlassian.net/browse/PD-3726
The issue described in this ticket affects all items utilizing the mask-markup, including Inline Dropdown, Drag in the Blank, and Constructed Response components. Upon investigation, I determined that this issue predates the current math rendering accessible implementation and can be reproduced in versions from over a year ago. The core of the problem was that changes to the markup did not trigger updates in the MathJax-rendered content. This was due to the pre-existing MathJax containers that were already present in the DOM and were not being reset upon updates. Consequently, MathJax did not recognize these changes, treating the math content as already rendered and thereby skipping the re-rendering process.
The solution involved …
> fix(mask-markup): Clear MathJax containers and reset LaTeX on markup updates for accurate re-rendering PD-3726

- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/__tests__/__snapshots__/editor-and-toolbar.test.jsx.snap
- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/editor-and-toolbar.jsx
https://illuminate.atlassian.net/browse/PD-3834
related: https://illuminate.atlassian.net/browse/PD-2455
Added a condition to check if the related target is a button before focusing the editor. This prevents the editor from stealing focus when interacting with the special character keypad or other toolbar buttons.
> fix(editable-html): prevent editor from regaining focus when using Spanish or special character keypad PD-3834

- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-3653
There was this edge case that only happens when the response area had no space after the next content causing layout problems at dragging.
Before the fix:
https://github.com/pie-framework/pie-lib/assets/26737238/ffd6ccb3-2c97-4a6d-a952-999e2c5a7bca
After the fix:
because of the 'whitespace: nowrap' attribute the whole content: (response area + .) was moved in the next line.
https://github.com/pie-framework/pie-lib/assets/26737238/e1c250d7-f88b-4f94-a525-37e5fbfe04d8
> fix(drag-in-the-blank): prevent line wrapping for response area PD-3653

- packages/pie-toolbox/src/code/charting/mark-label.jsx
https://illuminate.atlassian.net/browse/PD-3799
With the fix:
https://github.com/pie-framework/pie-lib/assets/26737238/7808fea7-b0b0-4217-9e8e-69c108ff8ff5
> fix(charting): Evaluate should not mark up category labels as correct/incorrect when they are not editable PD-3799

- packages/pie-toolbox/src/code/editable-html/__tests__/editor.test.jsx
- packages/pie-toolbox/src/code/editable-html/editor.jsx
https://illuminate.atlassian.net/browse/PD-3924
This resolves the issue where the editable HTML labels on the graph remain editable and move back to the left after clicking the done mark, which should finalize the label position and stop editing.
> fix(graphing): Prevent editor from gaining focus after clicking Done on axis labels PD-3924

- packages/pie-toolbox/src/code/math-toolbar/math-preview.jsx
https://illuminate.atlassian.net/browse/PD-3627
NOTE: This workaround adds `!important` to enforce the correct positioning and styling
of `.mq-overarrow.mq-arrow-both` elements in MathQuill. This ensures consistent display
regardless of the order in which MathQuill is initialized on our websites.
In the future, investigate why MathQuill scripts and styles are being initialized
more than once and address the root cause to prevent potential conflicts and ensure
optimal performance.
> fix(math-preview): enforce consistent styling for MathQuill elements PD-3627

- packages/pie-toolbox/src/code/mask-markup/choices/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-3950
The corners are now just a slightly round in order to match the choices and response areas from the authoring view
> feat(drag-in-the-blank): use right-angle corners for answer choices & response areas PD-3950

- packages/pie-toolbox/src/code/editable-html/editor.jsx
https://illuminate.atlassian.net/browse/PD-2450
- Added a `label` element with a `for` attribute to the editor wrapper to associate it with the editor for accessibility purposes.
- Included an `id` attribute in the editor's container `div` to match the `for` attribute in the `label`.
- Ensured the `label` is conditionally rendered only if the editor is a response-area-editor in extended-text-entry
- Styled the `label` with `srOnly` class to visually hide it but keep it accessible for screen readers.
> feat(editable-html): Add accessible label to extended-text-entry, response-area editor for improved accessibility PD-2450

- packages/pie-toolbox/src/code/drag/placeholder.jsx
- packages/pie-toolbox/src/code/mask-markup/choices/choice.jsx
Avoid allocating more vertical space & provide a light gray fill (#ECEDF1) for the answer choice “pool” area
Screenshots are provided in the ticket:
https://illuminate.atlassian.net/browse/PD-3944
> Feat(categorize,drag-in-the-blank,ica,match-list): "pool" area changes

- packages/pie-toolbox/src/code/drag/placeholder.jsx
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
This story is to change the Gather and authoring empty response area design treatment for these item types to a dashed black stroke with a white fill: 
categorize
drag-in-the-blank
match-list
placement-ordering (when "placementArea" is true)
More details can be found in the task's description: 
https://illuminate.atlassian.net/browse/PD-3946
> Feat(categorize,drag-in-the-blank,match-list,placement-ordering) empty response area changes - dashed black stroke with a white fill 

- packages/pie-toolbox/src/code/plot/__tests__/__snapshots__/root.test.jsx.snap
- packages/pie-toolbox/src/code/plot/root.jsx
https://illuminate.atlassian.net/browse/PD-3791
"At present, the total amount of padding added is correct, but all the horizontal padding gets added to the right, and all the vertical padding gets added to the bottom. "
After the fix:
> fix(graphing): fixed padding from domain and range PD-3791

- packages/pie-toolbox/src/code/editable-html/editor.jsx
fix: removed code that messes up enter and caret in the editor [PD-4361]
> fix: removed code that messes up enter and caret in the editor [PD-4361]

- packages/pie-toolbox/src/code/mask-markup/components/__tests__/blank.test.js
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-4394
The change was made to ensure the content inside the span element has a more natural, non-narrow width. By temporarily setting the rootRef width to 'auto', it allows the width to be calculated based on the content.
> Fix(ditb) adjust width for longer text-based answer choices PD-4394

- packages/pie-toolbox/src/code/drag/__tests__/__snapshots__/placeholder.test.jsx.snap
- packages/pie-toolbox/src/code/drag/droppable-placeholder.jsx
- packages/pie-toolbox/src/code/drag/placeholder.jsx
The `isVertical` property makes sure that the pool is displayed in a flex column way for left or right arrangement of the choice pool in ICA. 
The `minHeight` property is used for this vertical display, to "stretch" the pool.
https://illuminate.atlassian.net/browse/PD-4387 
example:
> feat(drag): for ICA choice pool, add isVertical and minHeight props PD-4387

- packages/pie-toolbox/src/code/drag/preview-component.jsx
https://illuminate.atlassian.net/browse/PD-4548
The problem: 
When dragging and dropping a token, the droppable area initially turns grey as expected. However, if the token is slightly moved while still within the droppable zone, the area loses focus and reverts to its default state. This behavior prevents the token from being dropped, even though it visually appears to be inside the droppable zone.
A screen recording demonstrating the issue is available in the task's comment section.
The fix: 
`TouchOffset` was introduced as a simple adjustment to correct the calculated touch position during drag-and-drop interactions on touch devices.
> fix(drag): Fix touch position handling with zoom adjustment and offset PD-4548

- packages/pie-toolbox/src/code/editable-html/__tests__/editor.test.jsx
- packages/pie-toolbox/src/code/editable-html/editor.jsx
- packages/pie-toolbox/src/code/mask-markup/constructed-response.jsx
https://illuminate.atlassian.net/browse/PD-4618
1. In ECR response areas, response areas must be wide enough to accommodate the specified number of characters - for that I've adjusted editor to support calc expressions and ch units.
2. In ECR Gather, the Return/Enter key should be ignored.
> fix(ECR): enhance valueToSize in editor to handle calc expressions and ch units PD-4618

- packages/pie-toolbox/src/code/mask-markup/choices/choice.jsx
- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
https://illuminate.atlassian.net/browse/PD-4607
`white-space: pre-wrap` was causing issues and I did not found a reason for it. 
If we have multiple white spaces inside the chip label, the browser treats these as additional inline content that needs layout accommodation when using pre-wrap.
By changing the `white-space: pre-wrap` to `white-space: normal`,  wrapping will still happen, but only as needed based on content and container width.
I tested math content, image content and some models and it seems fine. Hopefully no DIB item needs the pre-wrap.
Item with the issue: 
Before:
After:
> fix(mask-markup): use whitespace normal for chip labels PD-4607

- packages/pie-toolbox/src/code/mask-markup/components/blank.jsx
Findings: https://illuminate.atlassian.net/browse/PD-4394
Problem: If math elements were already placed in tokens but MathJax had not finished rendering the equations, the height calculated to accommodate the math equations was incorrect due to incomplete rendering.
Solution: Recalculate and update the dimensions of tokens after MathJax completes rendering the equations
> fix(blank): Fix MathJax rendering issue PD-4394

- packages/pie-toolbox/src/code/editable-html/plugins/toolbar/editor-and-toolbar.jsx
Updated overflowY property from 'scroll' to 'auto' to improve scrollbar behavior. On Windows, the scrollbar was always visible, even when content didn't require scrolling, resulting in unnecessary space usage. With 'auto', the scrollbar now only appears when needed, ensuring a cleaner layout.
https://illuminate.atlassian.net/browse/PD-4618
> fix(editor-and-toolbar): Changed overflowY from 'scroll' to 'auto' for dynamic scrollbar PD-4618

- packages/pie-toolbox/src/code/drag/preview-component.jsx
https://illuminate.atlassian.net/browse/PD-4766
`color.borderDark()` is used in a style in pie-elements for ICA. For some reason on IPad, this is the style that is overwriting the pie-elements style, so I changed from `color.primary()` to `color.borderDark()` to match the one visible on web.
> fix(drag): use same border color ica on drag PD-4766

- packages/pie-toolbox/src/code/render-ui/preview-prompt.jsx
https://illuminate.atlassian.net/browse/PD-4917
> Fix: restore vertical layout of <p> tags in multiple-choice answer choices by setting flex-direction: column PD-4917

- packages/pie-toolbox/src/code/drag/preview-component.jsx
The style before was not matching the style that is applied when the choice is not dragged. It should be the same.
This is not affecting laptop, only touch devices. 
https://illuminate.atlassian.net/browse/PD-4765
Before: 
After:
> feat(drag): fix style to be the same as chip PD-4765

- packages/pie-toolbox/src/code/math-rendering-accessible/render-math.js
- packages/pie-toolbox/src/code/math-rendering/render-math.js
https://illuminate.atlassian.net/browse/PD-4561
this is not an interactive item, so we don't want tab navigation to pick it up
> feat(math-rendering): remove mathml from tab navigation PD-4561

- packages/pie-toolbox/src/code/charting/axes.jsx
- packages/pie-toolbox/src/code/charting/bars/common/bars.jsx
- packages/pie-toolbox/src/code/charting/common/drag-handle.jsx
- packages/pie-toolbox/src/code/charting/line/common/drag-handle.jsx
- packages/pie-toolbox/src/code/charting/plot/common/plot.jsx
https://illuminate.atlassian.net/browse/PD-5198 
em is set to 10px in IBX and box-sizing is set to border-box, which means that width/height include content + padding + border and it's breaking the svg.
Adding "unset" reverts to content-box → width/height only include the content, not padding or borders.
> fix(charting): add px values for MUI svg PD-5198
